### ISSUE TITLE
qTranslate Reset problem and returns errors

### ISSUE THREAD

**Issue by pedro-mendonca** [qTranslate-Team/qtranslate-x#101]
Version 3.2.9.2

After upgrade from 3.2.9 to 3.2.9.2, when I try to reset qTranslate-x it won't reset and returns errors in these lines:
Warning: Invalid argument supplied for foreach() qtx_configuration.php on lines 39, 40, 41, 42 and 43.

**Comment by johnclause** [comment]
Thanks! Try the latest again: https://github.com/qTranslate-Team/qtranslate-x/archive/3.2.9.3.zip. We will reopen the issue if it still occurs.

**Comment by pedro-mendonca** [comment]
Resetting just great again in 3.2.9.3! :+1: 
Thanks :D
