### ISSUE TITLE
Admin Language Switcher is not working consistently

### ISSUE THREAD

**Issue by pedro-mendonca** [qTranslate-Team/qtranslate-x#103]
After upgrading from v.3.2.9 to v.3.2.9.2 the admin language switching button is working inconsistently.

When I switch from one language to another one, some strings are translated to the just selected language and others are obtained from a previously used language that was somehow kept in memory, even if it's not enabled anymore.

Before upgrading, the switching was perfect and complete. After upgrading to 3.2.9.2 it's somehow messy.

**Comment by johnclause** [comment]
This should be fixed in 3.2.9.3: https://github.com/qTranslate-Team/qtranslate-x/archive/3.2.9.3.tar.gz, currently the latest on github. Let us re-open it if you find more inconsistencies.

**Comment by pedro-mendonca** [comment]
This looks stable now in 3.2.9.3 :+1: 
I've tested it with and without wordpress SEO (by yoast) and the bridge plugin from qtranslate team. :)
