### ISSUE TITLE
compatibility: qtrans_join missing?

### ISSUE THREAD

**Issue by nkint** [qTranslate-Team/qtranslate-x#106]
Hi! in q translate meta it is calling qtrans_join. is it missing in compatibility function?

**Comment by nkint** [comment]
maybe a compatibility function van be found here:

https://github.com/funkjedi/acf-qtranslate/blob/master/compatibility/qtranslatex.php#L17

**Comment by johnclause** [comment]
I added it to compatibility list. Will be in the next release or can be [downloaded](https://github.com/qTranslate-Team/qtranslate-x/archive/master.zip) from the latest from [GitHub](https://github.com/qTranslate-Team/qtranslate-x).
