### ISSUE TITLE
Question: Possible to use get_page_link($id) or get_permalink($id) to get a link for a target language?

### ISSUE THREAD

**Issue by alancwoo** [qTranslate-Team/qtranslate-x#118]
As the title explains, I was wondering if there's a way to use `get_page_link($id)` or `get_permalink($id)` to get a link in a target language?

For example, on a `German page`, to have a link to another page that is in `English`.

(The use case here is a splash page with a choice of languages that takes you to another page in either German or English)

**Comment by johnclause** [comment]
You can pass URL through `qtranxf_get_url_for_language($url,$lang,true);` to get it in language needed. Is this what you meant?

**Comment by johnclause** [comment]
I assume it is closed, we can still write to closed issue, and may reopen it if needed.
