### ISSUE TITLE
Categorie Names containing an apostrophe break

### ISSUE THREAD

**Issue by richpav** [qTranslate-Team/qtranslate-x#122]
Version 3.2.9.8.3

If a category is named "Children's Courses" it won't display in Japanese and the Japanese translation can't be changed; it remains in English. Removing the apostrophe, the English name of the category is correct (e.g. "Courses for Children") and the Japanese name changes to "Children\’s Courses". I messed around with it a bit and more backslashes kept being added to the string. By avoiding apostrophes everything works fine.

**Comment by johnclause** [comment]
Please, use the latest fom the GitHub version: https://github.com/qTranslate-Team/qtranslate-x/archive/3.2.9.8.4.zip. I am closing this issue for now, we can still write into a closed issue, or we can re-open it, if needed.
