### ISSUE TITLE
Language not set - appear in admin panel

### ISSUE THREAD

**Issue by wocmultimedia** [qTranslate-Team/qtranslate-x#144]
I have some problem with the plugin. I installed this morning the beta release from github how suggested in this wp support post https://wordpress.org/support/topic/is-it-compatible-with-wp-42?replies=8#post-6866912
Anything worked fine but looking at the admin panel in All Pages and All Posts panels, some pages and some posts as well as all new pages and new post appear how "Language not set" look at the <a href="http://www.wocmultimedia.biz/repository/languageNotSet.jpg">screenshot</a>
Any suggestion?

Thanks

**Comment by johnclause** [comment]
I think the WP thread already has an answer:  https://wordpress.org/support/topic/is-it-compatible-with-wp-42. Copied here:

There is nothing wrong with "Language not set". It is a new feature, unrelated to WP 4.2.

It shows "Language not set" for posts which do not have content or if content is exactly the same for all languages. Means that such a post/page does not have content yet different by language. If you turn on Editor Raw Mode, you will see no language tags, which is "Language not set".

I found it helpful for myself to see which pages do not have content yet in the list of pages. Before this change, it would show all languages for such pages, which was even more confusing.

I hope it resolves this, I am closing now, we can still write to closed issue and may re-open it when needed.

**Comment by raykai** [comment]
ya but there is a bug too.

If you have a sub-page of the one that is marked as "Language not set" the breadcrumb will display both languages at the same time if both languages have the same content see this:
![bug](https://cloud.githubusercontent.com/assets/8138894/21085122/63e4b0e2-bfdb-11e6-8bb6-ed1d1a25eb16.JPG)
