### ISSUE TITLE
Not possible to switch to the default language URL

### ISSUE THREAD

**Issue by taai** [qTranslate-Team/qtranslate-x#147]
I have noticed that sometimes it is not possible to switch to the default language URL which has no language code in it (when using ```Hide URL language information for default language.``` option).

To test it go to "http://example.com/de/testpage" and then to "http://example.com/testpage" - it redirects back to "http://example.com/de/testpage".

To fallow the logic in this plugin was not easy, but I found the solution. Check my pull request!

**Comment by johnclause** [comment]
This is by design: https://qtranslatexteam.wordpress.com/2015/02/26/browser-redirection-based-on-language/

**Comment by taai** [comment]
@johnclause Alright. I wish I knew this earlier.

But what if I opt-in ```Disable language client cookie "qtrans_front_language"```? Can my solution be useful in that case? If yes, just another variable has to be checked...

When cookies are disabled, weird things happens... :laughing:

**Comment by johnclause** [comment]
When cookies are disabled, it may not always work correctly in a complex configurations, but is expected to work fine in a simple configuration. I think, this is mentioned in the document too.
