### ISSUE TITLE
Eternals URL (subdomains) are also translated

### ISSUE THREAD

**Issue by jcchavezs** [qTranslate-Team/qtranslate-x#148]
Let say the wordpress URL is http://domain.com with two languages: English and Norwegian.

If I add an external menu item whose URL is a subdomain (non-wordpress related), http://sub.domain.com, then per each language, the translated URL will be:

English: http://sub.domain.com/en/
Norwegian: http://sub.domain.com/no/

This is of course not a desirable behaviour and I can not think of a case where this is the proper behaviour.

**Comment by johnclause** [comment]
Thank you very much, José, for report and pull request. I guess this can be closed now? We can still write into closed issue or may re-open it if needed.
