### ISSUE TITLE
only one language is visible at Yoast SEO settings

### ISSUE THREAD

**Issue by vonsch76** [qTranslate-Team/qtranslate-x#154]
A minor issue, but still an issue.

Tried to tune Yoast Seo setting, but only one language is visible. (Have 2 on the page.) As the flag is missing from there can not change between the languages.

**Comment by johnclause** [comment]
I cannot reproduce this. Version? If this is still an issue, please, provide the steps to reproduce, preferably under the standard as simple as possible configuration.

**Comment by vonsch76** [comment]
John, version is all the latest (qT-X 3.3, WC 2.3.8, WC & qT-X 1.1, WP SEO
2.1.1, WP SEO & qT-X 1.0.0). The issue seems to be that the language
switcher button changes only the most important keyword (second line), not
the rest.

Hungarian
[image: Inline images 1]

English
[image: Inline images 2]

You can do a live test on testenv.hajoznijo.hu, your account is still valid.

Cheers,
Kornel

**Comment by vonsch76** [comment]
John, you can close this. Seems that upgrade to WC 4.2.2 solved the problem and not everything works OK.

**Comment by johnclause** [comment]
I wish all issues would go away this way ;)
