### ISSUE TITLE
Same title & content for all languages -> all other languages empty

### ISSUE THREAD

**Issue by diego-betto** [qTranslate-Team/qtranslate-x#156]
If you want a post has the same title and the same content for all languages, the system does not consider the other languages and leaves empty

Maybe we need to change this [ from qtranslate_core.php (rows 1283-1286) ]

	foreach($texts as $lang => $t){
		if ( $t != $text )
			return null;
	}

**Comment by johnclause** [comment]
Please, provide the steps to reproduce the actual problem.

**Comment by johnclause** [comment]
I hope the issue is resolved, I am closing it, we can still write into closed issue and may re-open it if needed.

**Comment by thehung2224** [comment]
I have the same problem, please help me.
