### ISSUE TITLE
Can't remove cart item - Woocommerce

### ISSUE THREAD

**Issue by cnasikas** [qTranslate-Team/qtranslate-x#158]
Hi

I experience a weird problem. I can't remove an item from cart. I inspect the cookies and I see that the session cookies won't be removed when I remove the item. If I change language to the default language (English) the item can be removed(the url changes).

I spoke to Woocommerce support and they told me:

I can now see what the problem is; when attempting to remove an item from the cart, your translate plugin attempts to translate the URL, which prevents it from being removed from the cart:

You can see that it causes a redirect back to the cart page. The cart works fine using the language defined within WordPress(English), thus it appears to be working as it should. However, your translation plugin is preventing the items from being removed from the cart. WooCommerce is only designed to work with a single language. Because of this, I ask that you submit a support ticket with the developers of the plugin so that they can hopefully correct this and prevent the redirect from occurring.

Thanks in advance

**Comment by johnclause** [comment]
Wow, second submission ;) Let us continue under https://github.com/qTranslate-Team/woocommerce-qtranslate-x/issues/14
