### ISSUE TITLE
Add media and Text option disable after install the latest version

### ISSUE THREAD

**Issue by reansey** [qTranslate-Team/qtranslate-x#16]
Hello,

After I install the https://wordpress.org/plugins/qtranslate-x/ the latest version it disable the Add Media and Text option and I cannot post my content fine, so do you have any idea?

thanks

**Comment by johnclause** [comment]
Hi, did you place this topic in three different places? ;)  Let us continue here. I saw your reply on WP: "I used this version Version 2.9.6, and it not working in the default of wordpress text editor.". 

I assume you loaded 2.9.8.8?

No, I have no idea, it works for me. BTW, many people already tested it and nobody observed what you describe. Please, help us with as many details as you can think of.

Maybe some browser caching went wrong? Did you try to refresh or restart the browser? Does it behave like this in any browser? Does it happen under Twenty Fifteen with -x the only plugin?  Please, give me enough details so that I can reproduce.

**Comment by reansey** [comment]
where can download 2.9.8.8

**Comment by johnclause** [comment]
Which version did you try then?

**Comment by reansey** [comment]
Version 2.9.6

**Comment by johnclause** [comment]
2.9.8.8 is the latest from jithub

**Comment by reansey** [comment]
so I see it disable my Add media and Text Editor option, I can create one user for you if you want.

**Comment by johnclause** [comment]
You said it worked for you with 2.9.6 and them you upgraded to the latest?

**Comment by reansey** [comment]
I meant that version not working, and this my site http://camm-media.org/

**Comment by johnclause** [comment]
Which version did you have before?

**Comment by johnclause** [comment]
Just refresh the window in browser in 2.9.6

**Comment by reansey** [comment]
before I try qTranslate Plus and it got error and then change to your version and it disable Add Media and Text Editor option

**Comment by reansey** [comment]
I try to many thing and I dot not see it working, I think because of some script in the plugin, because I disable plugin I see every thing working fine.

**Comment by johnclause** [comment]
Wow, you really need to think before stating the problem ... Well, 2.9.6 should work ok, unless you got some new unknown yet combination of plugins to conflict. Did browser restart help?

**Comment by reansey** [comment]
I browse in 3 browser and got the same problem? I just want to know which version is the best?

**Comment by reansey** [comment]
do you want to check in my admin?

**Comment by johnclause** [comment]
The best is from github, as far as I can tell. it is alpha and I did not hear any bug reports except what is listed in "Known Issues" section of readme.txt. So you may review the readme before trying.

**Comment by reansey** [comment]
can you give me the link to download.

**Comment by johnclause** [comment]
Could you review the readme and see if you recognize any plugins you are using.

**Comment by johnclause** [comment]
It is here on github: https://github.com/qTranslate-Team/qtranslate-x/archive/master.zip

**Comment by johnclause** [comment]
readme: https://github.com/qTranslate-Team/qtranslate-x/blob/master/readme.txt

**Comment by johnclause** [comment]
Yes, if it not working for you, I would like to get admin.

**Comment by reansey** [comment]
I am also try that one and got the same. I think it got error from some script, I try to disable all the plugin it also not working.

**Comment by johnclause** [comment]
Ok, I ready for admin access ;)

**Comment by reansey** [comment]
http://camm-media.org/wp-admin/

user: admin
pass: abc123

**Comment by reansey** [comment]
ah you can login by no user from me?

**Comment by johnclause** [comment]
???

**Comment by reansey** [comment]
forget it. and can you login now?

**Comment by johnclause** [comment]
Yes, I am in. I will need some time. Can you let me be there alone for a while? I can create a separate username, then you can change the password for admin to something else, since this one got published here?

**Comment by reansey** [comment]
Ok, you can

**Comment by reansey** [comment]
But Hope every thing is fine

**Comment by reansey** [comment]
so please check and you past some here, I need to go now. thanks

**Comment by johnclause** [comment]
I switched the user to new one. You can change password on admn if you wish. Thank you, I will take a look at it.

**Comment by johnclause** [comment]
Hi Seng, I deactivated -x and same problem remained. This theme seems to be underdeveloped, it produces error messages like crazy, both on the screen and java console. There is a lot to figure out, and it is not related to qTranslate-X. Make it work without -X first, then we may continue on -X issues if there will be one. If you wish me to work on this theme, I will have to charge you on hourly basis. I hope you will figure it out. Good luck.

**Comment by reansey** [comment]
Hello,
Thanks to let me know, so let me update the theme.
