### ISSUE TITLE
Causes js error (v3.3.5)

### ISSUE THREAD

**Issue by Guntiss** [qTranslate-Team/qtranslate-x#164]
<b>Warning</b>:  json_encode() expects exactly 1 parameter, 2 given in <b>wp-content/plugins/qtranslate-x-master/admin/qtx_configuration.php</b> on line <b>359</b><br />
var qTranslateConfig=;

Likely because of older php version.

**Comment by johnclause** [comment]
Thank you, I put 'if' to fork by version. It will be in on next push.
I am curious which country still runs older versions of PHP? Or this is just a particular provider?
