### ISSUE TITLE
Language Switching Buttons stopped working

### ISSUE THREAD

**Issue by pedro-mendonca** [qTranslate-Team/qtranslate-x#170]
I'm on current v3.3.5

**Comment by johnclause** [comment]
Which page? Is it still a case in 3.3.6, the latest? You would probably need to re-save the configuration once, 3.3.6 hopefully does it automatically.

**Comment by pedro-mendonca** [comment]
Mostly on any content edit page. Now on 3.3.6 it's solved :+1: 
No need to re-save.

**Comment by Grafcom** [comment]
@pedro-mendonca
same problem as here?
https://wordpress.org/support/topic/not-showing-languages-for-postpages?replies=31

**Comment by pedro-mendonca** [comment]
Not as such, I didn't upgrade from mqTranslate recently, neither I had LSB disabled. Still the LSB didn't appear, probably a glitch in v3.3.5 in recent changes. Got solved in v3.3.6 as I've mentioned above.
Thanks @Grafcom :+1:
