### ISSUE TITLE
Unable to add custom languages without causing "Undefined index" error.

### ISSUE THREAD

**Issue by taai** [qTranslate-Team/qtranslate-x#171]
I have added an Austrian language and chosen "at" language code. I know that in Austria they speak German, but still - I need to use "at" as a language code...

"qTranslate X" throws this error:

```
Notice: Undefined index: at in /public/wp-content/plugins/qtranslate-x/qtranslate_hooks.php on line 36
```

Appearently there is no arra key "at" in the array returned by ```qtranxf_default_windows_locale()``` function, so this line throws that error:

```php
$locale[] = $windows_locale[$lang];
```

So, how to add custom (unlisted in this plugin) languages? Would you add some filter in ```qtranxf_default_windows_locale()``` function or figure out some better way?

**Comment by johnclause** [comment]
Thank you for the report. I changed this line to
>if(isset($windows_locale[$lang])) $locale[] = $windows_locale[$lang];

If "Locale" for language itself is set meaningfully, then it should work ok even with this waring.

Does it work for you regardless this message?

**Comment by taai** [comment]
@johnclause I think it should work without checking that the key exists. But it had to be fixed. Thank you! :+1:

**Comment by johnclause** [comment]
This is the only place where 'windows_locale' is in use, and if Windows does not have this code there is no neither need nor way to make it up meaningfully.
