### ISSUE TITLE
Trying to get i18n-config-profile.json to work

### ISSUE THREAD

**Issue by richpav** [qTranslate-Team/qtranslate-x#177]
I took the simple i18n-config-profile.json John wrote and tried to make the "nickname" field translatable. Didn't work. What am I doing wrong?

```
{"vendor":{"plugins/qtranslate-x":"1.0"},
"admin-config":{
	"profile":{
		"pages":{"profile.php":""},
		"anchors":{"nickname":{"where":"before"},"description":{"where":"before"}},
		"forms":{
			"main":{
				"fields":{
          "nickname":{},
					"description":{}
				}
			}
		}
	}
}
}
```

**Comment by johnclause** [comment]
I do not see anything wrong, your file worked for me. How did you enable it, did you put filename in "Configuration Files" or did you enter it in "Custom Configuration"?

**Comment by richpav** [comment]
I don't know why it didn't work earlier, but it works now. It's like how the wife can't get the car to start, so she tells her husband, then he tries and it starts right up.

**Comment by johnclause** [comment]
:+1:
