### ISSUE TITLE
Menu not adding items

### ISSUE THREAD

**Issue by juandelospalotes** [qTranslate-Team/qtranslate-x#181]
Hi, I am creating a site for a friend, first I created it in my hosting, in my wordpress instalation, I have visual composer wp bakery installed, your plugin and WPBakery Visual Composer & qTranslate-X. Everything was ok. When I imported the content in his wordpress, (previously I installed your plugin) I started having problems. When I wanted to modify a page I got this error: Fatal error: Only variables can be passed by reference in /home/odvnebhg/htdocs/wp-content/plugins/qtranslate-x/admin/qtx_configuration.php on line 52 If I deactiveted the plugin I could make the changes. Another problem is that I ticked hide title and colon in the widget, it unticked it when I punch save, and instead of showing just the flags it showed: Language: and the flags. It drove me crazy so I decided to create a new database and to re install wordpress, and creating it all again, but now it doesn't even let me to add items to de primary menu or any other menu that I create. Do you know what could cause these problems? How can it be solved? I am going crazy with these problems. Thank you very much

**Comment by johnclause** [comment]
Which PHP and qTranslate-X versions do you run?

**Comment by juandelospalotes** [comment]
The problem has been solved by updating php version. 
I have another problem, my wordpress instalation is in english, but when I activate the plugin my wordpress changes to german language. The hosting is in Germany. I don't know how to solve it.
Thank you for your answer

**Comment by johnclause** [comment]
Which version of PHP did you upgrade from? I need to know what is not compatible. 

>wordpress changes to german language
how to solve it.

Please, describe what you need to solve. When you enabled a few languages, you may switch WordPress admin to any of them via language menu at the top right corner. Does this help?

**Comment by johnclause** [comment]
I am closing this issue for now, we can still write into a closed issue, or we can re-open it, if needed.
