### ISSUE TITLE
error after 45 menu items

### ISSUE THREAD

**Issue by brizeglace** [qTranslate-Team/qtranslate-x#187]
Hello,

when i add a menu item after 45 menu items, i have this error :
Fatal error: Cannot unset string offsets in /............/wp-content/plugins/qtranslate-x/admin/qtx_configuration.php on line 47

Add menu items work with the pluginis  disable.

Thanks for your response.

**Comment by johnclause** [comment]
Is this repeatable or was it one time occurrence? Does it work again after browser restart or something like this? Memory resources? Which kind are those menu entries mostly, pages, tags, posts, etc.? I mean, which kind I should try to add 45 times in order to reproduce it?

**Comment by brizeglace** [comment]
Hello John,

this is all the time, when in the admin panel i ad a nous item menu on an existing menu, font all type of post.

step 1 : goto /wp-admin/nav-menus.php
step 2 : Select page/post/Custom type on the right side
step 3 : clic on button Add to Menu
step 4 : Save menu

If you have less of 45 items on your menu, its, work, but if you have more then 45 items, you have a white page with this error :
Fatal error: Cannot unset string offsets in [SERVEUR LOCATION]/wp-content/plugins/qtranslate-x/admin/qtx_configuration.php on line 47

If i disable qtranslate x, it's work, and i can add more the 45 items.

**Comment by brizeglace** [comment]
Hello John,

Have you find a solution ?

also, if not, i need tu uninstall your plugin.

Now if i uninstall, i have an other pb, because i have after disable the plugin, i have this label on all content in my site [:fr]At the begining and [:] ta the end.

Have you a solution if i disable the plugin for my content.

Thank you.

**Comment by johnclause** [comment]
No we have not have a chance to look at it. Have you try to increase memory limit? Does the problem stay after you finish adding menu items? As a workaround, you may for now enter all menu items you need with qtx off and then turn it on to use translations?

**Comment by johnclause** [comment]
Have you followed the [troubleshooting guide](https://qtranslatexteam.wordpress.com/troubleshooting/)? I was trying adding items now (I have WP_DEBUG) and I started getting waring way before I reached fatal error:

>Warning: Input variables exceeded 1000. To increase the limit change max_input_vars in php.ini.

So, the instruction what to do is right there: "increase the limit max_input_vars in php.ini"
Your hosting provider will let you know how to do so on the server.

I am closing it for now, I believe this is the solution, but we can still write into a closed issue or can re-open it if necessary.

**Comment by brizeglace** [comment]
Hello John, i have allready change this param in my php.ini, and it's it's work without the plugin.

I want to disable qTranslate to use an other plugin, but, if i dissable your plugin, i have in my content of my site [:fr]At the begining and [:] ta the end.

How it's possible to disable and don't have the préfix on my content ?

**Comment by Grafcom** [comment]
@brizeglace
you can use search and replace in the database.
