### ISSUE TITLE
Wordpress Navigation Menu!!

### ISSUE THREAD

**Issue by yavuzwb** [qTranslate-Team/qtranslate-x#188]
Hello, 

I'm using Wordpress 4.2.2. I have a little problem. My problem is about the Navigation Menu.

I am going to add the menu Appearance >> Menus. When I add the "Contact Us" page on the Menus, its Ok. 

But after the click "Save Menu", it doesn't accept. I added 7 page no problem. When I add one more, its not saving. 

But when disable QTranslate-X, its working well and I can add 8 page. 

How can I solve this problem?

**Comment by Grafcom** [comment]
@yavuzwb
without qTranslate you can create more than 8 pages? Please try how many.
Thanks

**Comment by johnclause** [comment]
Have you tried to follow https://qtranslatexteam.wordpress.com/troubleshooting/?
You may need to increase max_input_vars in php.ini.

**Comment by johnclause** [comment]
I assume it is resolved. We can still write into closed issue and can re-open it if necessary.
