### ISSUE TITLE
Menu apearance changed after update

### ISSUE THREAD

**Issue by ordin2342** [qTranslate-Team/qtranslate-x#194]
After installing the recent update the apearance in the menu changed. Before it was like "en/it", now there's the word "Language" (in the current language) written out in the menu instead. How can you change it back?

**Comment by johnclause** [comment]
It was not supposed to show en/it to begin with unless you configured it so, or there is some unexpected behavior. Menu configuration options are listed in FAQ: https://qtranslatexteam.wordpress.com/faq/#LanguageSwitcherMenuConfig

**Comment by ordin2342** [comment]
Thank you for clarifying. I've read through the FAQ before, but I don't 
see an option to configure it to display either a custom text or an 
abbreviation of the languages. Could you please explain how to do that?

Thanks.

**Comment by johnclause** [comment]
Please, clarify what you mean.

**Comment by ordin2342** [comment]
How can I set the word that's displayed by qtranslate-x in the menu on 
the website? The "#qtransLangSw?" - string doesn't seem to provide an 
option for this. Let's say I want it to be "Languages available" so the 
menu will look like this:

Languages available
|_ English
|_ Italian

**Comment by johnclause** [comment]
Use "#qtransLangSw?colon=hidden&flags=items" and put "Languages available" in "Navigation Label" of menu item editor.
