### ISSUE TITLE
Infinite redirect loops when using buddypress or other plugins

### ISSUE THREAD

**Issue by dingzj** [qTranslate-Team/qtranslate-x#195]
I found the infinite redirect issue with BuddyPress, and don't know why. After a few hours of debugging, finally, here is the reason.
I have Nginx for my config, and has the following rules:
```
location / {
    try_files $uri $uri/ /index.php?q=$uri&$args;
}
```
which is pretty common in many WP environment configuration. 

However, this leads to many infinite redirect loops for some of my BuddyPress pages (some pages are fine). 

I notice that the _SERVER[REQUEST_URI] and _SERVER[QUERY_STRING] will be different, triggering the infinite redirections. 
An example of the two values in _SERVER VALUE:
```
[REQUEST_URI] => /zh/activity?r=user1&_wpnonce=8aae8e30c0
[QUERY_STRING] => q=/zh/activity&r=user1&_wpnonce=8aae8e30c0
```

I end up trace up the source and patch it in `qtranxf_buildURL` function in the qtranslate_util.php file, by checking the `wp-path` and `query` value to remove the duplication of wp-path

**Comment by johnclause** [comment]
Is this still a problem under the latest qtx? I am closing this issue for now to save the future clicks, we can still write into a closed issue, or we can re-open it, if needed.
