### ISSUE TITLE
qtranslate-x.3.4.1 Different Permalinks per Language ?

### ISSUE THREAD

**Issue by jkamuf2s** [qTranslate-Team/qtranslate-x#197]
Hi, I have the following Site with 2 Languages: German and English.

I have a page called "Directions" in English and "Anfahrt" in German, now I want that in the Browser URL if I display the german site the path is "domain/anfahrt" and in the english site "domain/directions"

![screenshot 5603](https://cloud.githubusercontent.com/assets/7395542/8675039/f2de21c4-2a41-11e5-8945-9b787c3cd8c7.jpg)

Is this possible ? If yes, can you help me with the easiest way to implement it :) 

Thanks a lot !

**Comment by johnclause** [comment]
There is no easy way to implement it. There is plugin [QTranslate Slug](https://wordpress.org/plugins/qtranslate-slug/), which may help, but it is not 100% compatible with qTranslate-X, although people say it is usable: https://qtranslatexteam.wordpress.com/2015/05/15/release-notes-3-4/

It may be implemented natively under qtx some day.

**Comment by jkamuf2s** [comment]
Worked for me with Qtranslate Slug 1.1.16
