### ISSUE TITLE
redeclare qtranxf_trim_words

### ISSUE THREAD

**Issue by faina09** [qTranslate-Team/qtranslate-x#201]
PHP Fatal error:  Cannot redeclare qtranxf_trim_words()
 (previously declared in ..\wp-content\plugins\qtranslate-x\admin\qtx_admin_utils.php:643) 
in ..\wp-content\plugins\qtranslate-x\qtranslate_frontend.php on line 657

**Comment by Grafcom** [comment]
@faina09 
same as this?
https://wordpress.org/support/topic/cannot-redeclare-qtranxf_trim_words?

**Comment by faina09** [comment]
yes, I solved editing
\wp-content\plugins\qtranslate-x\admin\qtx_admin_utils.php
inserting the if line @line 642

if(!function_exists('qtranxf_trim_words')){
//filter added in qtranslate_hooks.php
function qtranxf_trim_words( $text, $num_words, $more, $original_text ) {
(....)



Stefano Cotterli

**Comment by johnclause** [comment]
Should fixed in 3.4.3
