### ISSUE TITLE
Qtranslate-x backend fields

### ISSUE THREAD

**Issue by Fibiuz** [qTranslate-Team/qtranslate-x#210]
Hi Guys,

I created an option page for my theme.
I'm wondering how can I add the qtranslate-X switcher and manage properly my settings fields in order to avoid to put each value with the syntax [:en]some english value[:de]some deutch value etc...

Thanks

**Comment by Grafcom** [comment]
@Fibiuz 
maybe this can help you further: https://qtranslatexteam.wordpress.com/integration/
Success

**Comment by johnclause** [comment]
@Fibiuz: I believe @Grafcom answered your question, and I am closing the issue for now, we can still write into closed issue and can reopen it if needed.
