### ISSUE TITLE
how to prevent auto redirection on certain page

### ISSUE THREAD

**Issue by bung87** [qTranslate-Team/qtranslate-x#211]
I have seperated wordpress login.php to serveral files ,
in the wp root directory I have
 /auth/login.php
while use default language it works fine,
but while having language detection cookie it auto redirect to 
/en/auth/login.php
which would causes  page not found error,
how to resolve this issue?

**Comment by Grafcom** [comment]
@bung87
en/ is not your default language?

**Comment by bung87** [comment]
default language is chinese.

**Comment by Grafcom** [comment]
Delete cache and cookies to access clean the site.
When you have - Detect the language of the browser and redirect accordingly. - and it goes to English you must choose Chinese manual to override the cookie settings.

**Comment by bung87** [comment]
so the simple way is disable this option,but this option is unchecked,it always set the language cookie.

**Comment by Grafcom** [comment]
If the browser is English for those who want to login then they will have first switched to the default language. 
Read also this:
https://qtranslatexteam.wordpress.com/2015/02/26/browser-redirection-based-on-language/

**Comment by bung87** [comment]
That would be a problem,I think wordpress system allow me to create custom page with wordpress core,but the redirection moves a page that does not exsit,is there a way disable the plugin while access certain page?

**Comment by Grafcom** [comment]
Not that I know. But if the language is set to Chinese it will remember this. Regardless of the browser language.

**Comment by bung87** [comment]
I know that but while the browser prefer language is english that would be a problem,the user just can't login except swiching to Chinese first,users can't know about it.even they knew ,click one more time is awful.

**Comment by Grafcom** [comment]
You could use a plugin (just tested it)  https://nl.wordpress.org/plugins/theme-my-login/
Than the language does not matter, just type login or en/login. Both works

**Comment by bung87** [comment]
I tried it ,but it load si-recaptch.js over 10 times stil not finish loading page,after that I checked the original wp-login.php it works fine,I may re-do work on this file or copy auth files to en/auth,thanks for your help.

**Comment by Grafcom** [comment]
success

**Comment by bung87** [comment]
after copying auth files and index file to /en seems work fine,it's stupid but work out.
