### ISSUE TITLE
Comments error

### ISSUE THREAD

**Issue by 007dutchy** [qTranslate-Team/qtranslate-x#215]
Just translated my Dutch page in English.
Now the comments that were already under the dutch article give an error message under the english version:
Warning: Invalid CRT parameters detected in C:\domains\easygoingrotterdam.nl\wwwroot\wp-content\plugins\qtranslate-x\qtranslate_core.php on line 735
You can see it here:
http://www.easygoingrotterdam.nl/en/free-city-walks-rotterdam/

How can I fix this?

Thanks!

**Comment by johnclause** [comment]
I did not find the error on page linked, I hope it is resolved by now. We can still write into closed issue and may reopen it if needed.
