### ISSUE TITLE
PHP warning in qtx_admin.php on line 31

### ISSUE THREAD

**Issue by dirkgeeroms** [qTranslate-Team/qtranslate-x#217]
I recently installed qTranslate X on my wordpress website test.dirkgeeroms.be.
I got the following PHP warnings:
1) PHP Warning: Unknown: Input variables exceeded 1000. To increase the limit change max_input_vars in php.ini. in Unknown on line 0 
2) PHP Warning: Invalid argument supplied for foreach() in /www/test.dirkgeeroms.be/wp-content/plugins/qtranslate-x/admin/qtx_admin.php on line 31

The first one was easy to get rid off. But do I have to care about the second one? If so, how could I resolve it?

Cheers, Dirk

**Comment by johnclause** [comment]
Thanks a lot for the report. The first one is described in https://qtranslatexteam.wordpress.com/troubleshooting/, it is frequently a case when max_input_vars needs to be increased.

The second issue is a consequence of the first. If you still see the second warning, then yes, there is a problem which we need to attend on your configuration.

I am closing this issue for now, we can still write to closed issue and may reopen it when needed.
