### ISSUE TITLE
Bug on WP 4.3

### ISSUE THREAD

**Issue by Tusko** [qTranslate-Team/qtranslate-x#220]
TypeError: qTranslateConfig.qtx.addContentHooksTinyMCE is not a function

Have some error after wordpress update. Can't switch between visual/text tabs

**Comment by Tusko** [comment]
Found solution here
https://github.com/fburatti/acf-qtranslate

**Comment by aurukas** [comment]
where exactly?

**Comment by hubertinio** [comment]
The same in WP 4.6.1 and ACF-QTranslate 1.7.14
