### ISSUE TITLE
Gravity Forms

### ISSUE THREAD

**Issue by TERRY-FAGEN** [qTranslate-Team/qtranslate-x#221]
New install on staging server. What are the issues with gravity forms?

Warning: Invalid argument supplied for foreach() in /wp-content/plugins/gravityforms/forms_model.php on line 1445

Warning: Invalid argument supplied for foreach() in /wp-content/plugins/gravityforms/common.php on line 2833

**Comment by Grafcom** [comment]
@TERRY-FAGEN 
do you also use qTranslate support for GravityForms?
See here: https://wordpress.org/plugins/qtranslate-support-for-gravityforms/

**Comment by TERRY-FAGEN** [comment]
No, but I tried it and it caused more warnings so I removed it.

 

I even tried Formidable Forms and while it didn’t generate warnings or errors, it broke the template. The only plugin that seems to work without issues is Contact Form 7 but I’d like to keep Gravity Forms if I can.

**Comment by Grafcom** [comment]
Put your problem also on the support forum here: https://wordpress.org/support/plugin/qtranslate-support-for-gravityforms

**Comment by johnclause** [comment]
I also assume this belongs to other plugin, as @Grafcom mentioned. I am closing it now, we can still write into closed issue or can reopen it if needed.
