### ISSUE TITLE
WordPress Repository Status

### ISSUE THREAD

**Issue by mrwweb** [qTranslate-Team/qtranslate-x#222]
I see in the 3.4.3 changelog that the plugin was temporarily pulled from the WordPress.org repository (and still is as of August 22, 2015). Can someone give a status update on whether the security concerns are valid, whether they've been fixed, and if/when we can expect the plugin back in the repository?

**Comment by michael-milette** [comment]
I am looking for the plugin as well.

**Comment by Gersnij** [comment]
Me too! I installled the plugin on one site, and need it once more..

**Comment by MarcoNko** [comment]
I was looking for the plugin repository too, panic!
https://wordpress.org/plugins/qtranslate-x is not working,
when will it be back online?

**Comment by ianchanning** [comment]
Everything seems to have gone very quiet on this. Given that qtranslate-x is the recommended replacement for mqtranslate which is fully deprecated as of WordPress 4.3 this becomes more urgent

**Comment by adamlindqvist** [comment]
I'm also looking for the plugin! Hope to see it back soon.

**Comment by ianchanning** [comment]
N.B. Anyone can download the master branch and upload the zip file to get the plugin back. You'll also need to unzip qtranslate-x-master.zip, rename it to qtranslate-x and rezip it if you want to make sure the plugin gets updated properly when it is reaccepted into the WordPress plugins directory.

**Comment by Grafcom** [comment]
@mrwweb @michael-milette @Gersnij @MarcoNko @adamlindqvist and @ianchanning

We are currently investigating this, please have patience.
In the meantime you can use the solution described by @ianchanning.
Thank you!

**Comment by Gersnij** [comment]
I'glad @mrwweb has commented today that there is hope we will have this plugin back. Thank you. 
Still there is a risk using the bypass descibed by @ianchanning, since - at this moment - we have no clue whether it is a matter of days or months.

**Comment by ianchanning** [comment]
@Gersnij i think it's pretty risk free. Any reason for the plugin being taken down was because of a bug in the very old qtranslate plugin - but it doesn't exist in the qTranslate-X plugin. As long as you rename the downloaded directory and re-zip it before uploading it to your site via 'Plugins > Add New' then the plugin will work normally and then you'll get prompted to update the plugin once it's added back into the WordPress plugins directory.

@Grafcom let me know if I can help at all

**Comment by Grafcom** [comment]
@ianchanning
you have programming experience? Send me a private email to gu nu at mar ius - si roen d com
Thanks

**Comment by Gersnij** [comment]
Are you sure it should work that way? I followed the instructions (download the master from the link, unzip, rename the folder and underlying folder to qtranslate-x, zip again, add new plugin via upload), but it says - in Dutch:  unzipping, installing, package cannot being installed. No valid plugins found.

**Comment by Grafcom** [comment]
@Gersnij 
only the underlying folder (with the actual files) is the new (only) folder to zip. Then you get a new valid package.

**Comment by Gersnij** [comment]
@Grafcom Thanks! Installation succesfull, as expected.

**Comment by mrwweb** [comment]
I'm happy to install it via GitHub for now. I'm just looking for an
*official* confirmation that this is a temporary issue, that the plugin's
development will continue, and that someone is actively working to get it
back into the repository.


Mark Root-Wiley

MRW Web Design <http://mrwweb.com/>  /  info@MRWweb.com <info@mrwweb.com>
  /  206-745-2581 <2067452581> (Email Preferred
<http://mrwweb.com/contact/#email-preferred>)

t @MRWweb on Twitter <http://twitter.com/MRWweb>     f Facebook
<http://facebook.com/MRWweb>     in LinkedIn
<https://www.linkedin.com/in/markrootwiley/>     W WordPress.org
<http://profiles.wordpress.org/mrwweb>     g+ Google+
<https://plus.google.com/+MRWweb>

**Comment by mvandemar** [comment]
For those who didn't notice the above activity, it appears to have been pulled due to a valid vulnerability, which @ianchanning is working on fixing here:

https://github.com/qTranslate-Team/qtranslate-x/pull/230

**Comment by richpav** [comment]
Until development restarts here, is @ianchanning 's fork the best to to use?

**Comment by ianchanning** [comment]
I'm confident what I submitted should work and addressed the security concern that WordPress raised. I tested as best I could the fix I made, but I could have introduced a bug as this is my first time modifying the plugin.

* If you're worried about 100% functionality working - go with the current release version
* If you're worried about the fairly minor security flaw - go with my fork

**Comment by Grafcom** [comment]
@ianchanning 
on my test server your changes work, no errors discovered so far. :-)

**Comment by johnclause** [comment]
Sorry for the delay with security fix required by WP. The fix is now submitted and plugin should be back after WP approves it. I am closing it for now, we can still write into a closed issue and may re-open it again if  needed.

**Comment by johnclause** [comment]
https://qtranslatexteam.wordpress.com/2015/09/03/why-qtranslate-x-disappeared-from-wordpress-repository/

**Comment by michael-milette** [comment]
It's back on WordPress.org!

See https://wordpress.org/plugins/qtranslate-x/

Have a great weekend!

     Michael

**Comment by Gersnij** [comment]
Congrats. Nice job!
