### ISSUE TITLE
No live site preview in customizer

### ISSUE THREAD

**Issue by richpav** [qTranslate-Team/qtranslate-x#223]
This is happening with all my sites, with all plugins disabled except qtranslate-x enabled, and regardless of theme being used--even twentyfifteen. When I use the site customizer, the live preview of the site won't load. If I disable qtranslate-x, it works as expected.

I have an administrator guest account for http://qtranslate.kogaeikaiwa.com if you'd like to take a look.

**Comment by johnclause** [comment]
Hi Rich, do you mind testing the latest from [GitHub](https://github.com/qTranslate-Team/qtranslate-x)? The customize screen is supposed to work, but it is not integrated yet, you will see many fields in raw format. At least it should not crash and all fields are updateable in raw mode. Integration is the next step, for the future releases ...

**Comment by johnclause** [comment]
I am closing this issue for now, we can still write into a closed issue, or we can re-open it, if needed.
