### ISSUE TITLE
qtranslate-x is again missing from t he WordPress Repository

### ISSUE THREAD

**Issue by jimbocook** [qTranslate-Team/qtranslate-x#224]
The qtranslate-x plug-in seems to have gone missing again. Is there any word now hat the issue is this time or when it will be resolved?

**Comment by jimbocook** [comment]
Sorry duplicate question

**Comment by johnclause** [comment]
https://qtranslatexteam.wordpress.com/2015/09/03/why-qtranslate-x-disappeared-from-wordpress-repository/
