### ISSUE TITLE
Translating error message

### ISSUE THREAD

**Issue by derekyws** [qTranslate-Team/qtranslate-x#227]
I am using Avada with qtranslate X and WooCommerce for my estore. Because my store only allow customers to purchase 1 item at a time I inserted some lines in Avada's Theme.php to put on that restriction.
I manage to translate all my strings into multiple languages but I can't find a method to translate the error messages such as "Whoa hold up. You can only have 1 item in your cart"
Do I have to modify a PO file or are there different methods to translate these lines? Thanks

**Comment by johnclause** [comment]
po file is the easiest, or you can insert lines like __('[:en]EN[:de]DE[:]')

I am closing this issue for now to save the future clicks, we can still write into a closed issue, or we can re-open it, if needed.
