### ISSUE TITLE
Plugin disappeared from the Wordpress repository

### ISSUE THREAD

**Issue by fburatti** [qTranslate-Team/qtranslate-x#229]
The plugin has disappeared from the Wordpress repository, also the search does not find it.

![screen-qtranslate-github](https://cloud.githubusercontent.com/assets/248535/9469817/591aa67e-4b49-11e5-8ddc-ac2197acf183.jpg)

**Comment by Grafcom** [comment]
@ fburatti 
see also here: https://github.com/qTranslate-Team/qtranslate-x/issues/222
