### ISSUE TITLE
Text/Visual switcher doesn't work

### ISSUE THREAD

**Issue by Tusko** [qTranslate-Team/qtranslate-x#231]
Hi everyone! I have installed latest versions of qtranslate-x and wordpress. When I switched from visual editor to text I can't switch to Visual Editor again. Somebody can help?

**Comment by Grafcom** [comment]
@Tusko 
What other plugins do you use?
Deactivate them one by one and see if that makes a difference. If so hen activate them again one at a time.

**Comment by Tusko** [comment]
@Grafcom 
Find solution here
https://github.com/fburatti/acf-qtranslate
