### ISSUE TITLE
not working with ckeditor in wordpress

### ISSUE THREAD

**Issue by mt4c** [qTranslate-Team/qtranslate-x#233]
When use with the ckeditor plugin, the textarea is blank. Nothing shows up.

**Comment by Grafcom** [comment]
@mt4c
Read this: https://qtranslatexteam.wordpress.com/known-issues/
Try the Workaround since 3.3 If this not work we must put the plugin on this list https://qtranslatexteam.wordpress.com/incompatible/
Let us know.

**Comment by mt4c** [comment]
I'm sorry but it doesn't work after setting to the single language mode or with all other languages disabled.

**Comment by johnclause** [comment]
I updated page https://qtranslatexteam.wordpress.com/incompatible/ with this plugin.

@mt4c: please consider to take an initiative to integrate CK Editor with qTranslate-X: https://qtranslatexteam.wordpress.com/integration/, if it is importatnt to you.

Thank you.
