### ISSUE TITLE
qtranslate-x missing from Wordpress.org?

### ISSUE THREAD

**Issue by csmillie** [qTranslate-Team/qtranslate-x#235]
Hi,
I'm not able to find the plugin on Wordpress.org anymore:

https://wordpress.org/plugins/qtranslate-x/

Generates an error that the plugin cannot be found.  See screenshot:

![Uploading Screen Shot 2015-08-27 at 1.34.59 PM.png…]()

Was the plugin renamed or remove?  

Thanks,

Colin

**Comment by llynix** [comment]
See here:
https://github.com/qTranslate-Team/qtranslate-x/issues/222
