### ISSUE TITLE
Yoast SEO breadcrumbs: title not translated (comes out with language tags)

### ISSUE THREAD

**Issue by bmachuel** [qTranslate-Team/qtranslate-x#237]
Hi there,

I just migrated from qtranslate to qtranslate-x and am using Yoast SEO with breadcrumbs enabled.

The breadcrumbs anchor is fine, but the post or page title comes out in all 4 languages including languages tags (see http://www.staging1.fim-musicians.org/documents/norm-setting/fundamental-rights).

Many thanks in advance for your kind assistance.

Benoît

**Comment by bmachuel** [comment]
Problem solved:

Under import/export settings, select button "Convert database to the "square bracket only" style" and save.

That solves the SEO breadcrumbs issue described above (as well as same issue appearing in Top10 thumbnails titles).

**Comment by johnclause** [comment]
I wish every issue here would be self-solved :+1: Thanks you!
