### ISSUE TITLE
qTranslate-x plugin is no longer on Wordpress?

### ISSUE THREAD

**Issue by dereenb** [qTranslate-Team/qtranslate-x#242]
https://wordpress.org/plugins/qtranslate-x/ gives a "whoops" page... where is the plugin? How do I get it??

**Comment by Grafcom** [comment]
@dereenb
see also here https://github.com/qTranslate-Team/qtranslate-x/issues/222
Pleas close this ticket, thanks

**Comment by johnclause** [comment]
The latest version can be downloaded from GitHub: https://github.com/qTranslate-Team/qtranslate-x

**Comment by michael-milette** [comment]
It's back on WordPress.org!

See https://wordpress.org/plugins/qtranslate-x/

Have a great weekend!

 Michael
