### ISSUE TITLE
remove <meta name="generator"

### ISSUE THREAD

**Issue by bagaweb** [qTranslate-Team/qtranslate-x#244]
Sorry for writing here but I cannot reach the plugin page on wordpress.org anymore...
Just wondering if there's a way to remove the <meta name="generator" tag from header.
Thanks!

**Comment by johnclause** [comment]
>cannot reach the plugin page on wordpress.org anymore

https://qtranslatexteam.wordpress.com/2015/09/03/why-qtranslate-x-disappeared-from-wordpress-repository/

>way to remove the <meta name="generator" tag from header

This sounds like a request for a new option. Why would you care? This improves statistics, makes it easier to troubleshoot. Many plugins put this line, WordPress itself, WooCommerce, etc. I did not see an option to disable it in WordPress or Woocommerce, for example?

**Comment by bagaweb** [comment]
I see the plugin is back today.
I'd like to remove it for security reason.
For example it can be removed from WordPress using this function:
`remove_action( 'wp_head', 'wp_generator' );`

**Comment by johnclause** [comment]
Ok, I moved that line into a separate action: 'qtranxf_wp_head_meta_generator'
`remove_action('wp_head','qtranxf_wp_head_meta_generator');` should now remove it.
The action gets added within 'plugins_loaded' action, so you know the drill ...

Next time, I would appreciate, if you implement such simple thing yourselves and submit with a pull request at github.

Please, consider making donation: https://qtranslatexteam.wordpress.com/donations/, if you have not done so.

I am closing this issue for now to save the future clicks, we can still write into a closed issue, or we can re-open it, if needed.

**Comment by bagaweb** [comment]
Beautiful, thanks a lot!
I made a donation for your team.

**Comment by johnclause** [comment]
Thanks  lot!
