### ISSUE TITLE
HTML5 declaring language

### ISSUE THREAD

**Issue by Lesrad** [qTranslate-Team/qtranslate-x#245]
Hi John,

Is it possible to add the language of the post/page in HTML5 format?

i.e. html lang="en" or add lang="en" in another place that updates according to the pages primary language.

http://nimbupani.com/declaring-languages-in-html-5.html

http://stackoverflow.com/questions/7716144/where-to-specifiy-the-language-of-document-in-html-5-when-my-page-has-two-langua

Bing SEO report shows:

SEO Suggestion: 	The page is missing meta language information.

SEO Explanation: 	The Meta Language information is used as a hint to help us understand the intended language and country/region the page content applies to. This can help if your site is not hosted in the country/region. Use the “content-language” meta tag to embed the culture code in the <head> section of your page. For example, <meta http-equiv="content-language" content="en-gb"> indicates that the page is in English and intended for the the United Kingdom. Alternatively, you can use <html lang="en-gb"> or <title lang="en-gb">.

Recommended Action: 	Use <meta http-equiv="content-language" content="ll-cc"> tag in the <head> section of your page, where "ll-cc" stands for the culture code of the language and country/region the content applies to. Alternatively use the lang="ll-cc" attribute on either the <html> or the <title> tag .

**Comment by Lesrad** [comment]
Fixed it by adding
<html lang="<?php echo qtranxf_getLanguage();?>">

**Comment by johnclause** [comment]
The second line in source of every page is:
`<html lang="de-DE" itemscope="itemscope" itemtype="http://schema.org/WebPage">`
where "de-DE" is the language code. Is not it a case on your server?

>Bing SEO report shows

How exactly to get this report?

**Comment by Lesrad** [comment]
Seems fine with only <html lang="de">
Bing SEO : http://www.bing.com/toolbox/webmaster (need to login and only checks verified urls)
I don't get SEO errors after adding that code

site is:http://www.winallpoker.com/
https://validator.w3.org/nu/?doc=http%3A%2F%2Fwww.winallpoker.com%2Fde%2F
