### ISSUE TITLE
Uncaught ReferenceError: setTinyMceInit is not defined is thrown in Single Language Mode

### ISSUE THREAD

**Issue by reekrd** [qTranslate-Team/qtranslate-x#247]
Wordpress 4.3
qtranslate-x 3.4.4
(Chrome Version 45.0.2454.85 (64-bit))

Change Editor Mode to Single Language Mode. Add a new post or edit a post and the 'Add Media' button no longer responds. 

Output in the console when trying to Add New Post (post-new.php)

Uncaught ReferenceError: setTinyMceInit is not defined
addCustomContentHooks @ post-new.php:2058
(anonymous function) @ post-new.php:2058
m.Callbacks.j @ jquery.js?ver=1.11.3:2
m.Callbacks.k.fireWith @ jquery.js?ver=1.11.3:2
m.extend.ready @ jquery.js?ver=1.11.3:2
J @ jquery.js?ver=1.11.3:2

**Comment by johnclause** [comment]
I could not reproduce it so far, I am using the latest from GitHub: https://github.com/qTranslate-Team/qtranslate-x. Are you using one of WP standard themes?

**Comment by johnclause** [comment]
I was finally able to reproduce. The fix is in the latest version from GitHub: https://github.com/qTranslate-Team/qtranslate-x. This version also fixes crash in customize screen, still no integration on customize screen, but raw multilingual values should all work. Could you please test it?

**Comment by reekrd** [comment]
The 'Add Media' button now works in Single Language Mode.
