### ISSUE TITLE
Cross-Site Scripting 

### ISSUE THREAD

**Issue by Corentinfardeau** [qTranslate-Team/qtranslate-x#249]
Is the latest version of the qtranslate-x plugin resolve the XSS problems ? 

Best regards

**Comment by Lesrad** [comment]
Hi,
The plugin is back in the wp repo now here https://wordpress.org/plugins/qtranslate-x/ so I guess it is fixed also see here https://github.com/qTranslate-Team/qtranslate-x/commit/7528f845e0a0e321dc4fe587f222cd15cb692744
and here https://github.com/qTranslate-Team/qtranslate-x/commits/master

**Comment by Corentinfardeau** [comment]
Thank's for your quick response.

Best regards

**Comment by Corentinfardeau** [comment]
I have XSS issues with url injections due to the plugin . Example : http://www.wordpress.com/some-path/?><script>alert(0)<script> How can I prevent this injections ?

**Comment by johnclause** [comment]
Yes, it is fixed, otherwise WP would not put it back in the repository: https://qtranslatexteam.wordpress.com/2015/09/03/why-qtranslate-x-disappeared-from-wordpress-repository/
