### ISSUE TITLE
obsolete widget constructor

### ISSUE THREAD

**Issue by ursribi** [qTranslate-Team/qtranslate-x#250]
/* qTranslate-X Widget */

class qTranslateXWidget extends WP_Widget {

// obsolete constructor  in version wp 4.3. 
//	function qTranslateXWidget() {

// use this function in version wp 4.3
	function __construct() {
		$widget_ops = array('classname' => 'qtranxs_widget', 'description' => __('Allows your visitors to choose a Language.', 'qtranslate') );
// obsolete constructor call in version wp 4.3.
//		$this->WP_Widget('qtranslate', __('qTranslate Language Chooser', 'qtranslate'), $widget_ops);

// use this call in version wp 4.3
		parent::__construct('qtranslate', __('qTranslate Language Chooser', 'qtranslate'), $widget_ops);
	}

**Comment by johnclause** [comment]
Fixed in new soon to be released version 3.4.5, available from GitHub: https://github.com/qTranslate-Team/qtranslate-x
