### ISSUE TITLE
Garbled Chinese words

### ISSUE THREAD

**Issue by OscarAu** [qTranslate-Team/qtranslate-x#254]
The words become garbled after migration of database. The situation is like the following:
1)	When I type Chinese words and then click “UPDATE” when editing in the "PAGE"
2)     The Chinese words become garbled. for example: 測試-->??
3)     But if i input those chinese words in utp-8 form , after clicking UPDATE, it will turns into proper chinese words again. for example: &#x6E2C;&#x8A66;--> 測試
4)     However, converting all chinese words in utp-8 format is extremely time consuming. Please help~!

There is another problem:  Some fields provided by the theme cannot be edited in multi language. How can it be fixed?? THANK YOU!!!!
![20150911091501](https://cloud.githubusercontent.com/assets/14226969/9804933/9c324d12-5865-11e5-899b-c9ceff7e609a.jpg)

**Comment by johnclause** [comment]
>Some fields provided by the theme cannot be edited in multi language

https://qtranslatexteam.wordpress.com/integration/

>chinese words in utp-8 form

UTF-8 is what it is supposed to be as far as I understand. Update your keyboard driver. Maybe theme author can advise something why it is get broken. Does it work under one of the standard WP theme? If it does, then it is definitely the theme problem.

I am closing this issue for now to save future clicks, we can still write into a closed issue, or we can re-open it, if needed.
