### ISSUE TITLE
Empty menu item title messes up menu structure

### ISSUE THREAD

**Issue by cdauth** [qTranslate-Team/qtranslate-x#255]
In [qtranslate_frontend.php](https://github.com/qTranslate-Team/qtranslate-x/blob/master/qtranslate_frontend.php#L116), menu items with an empty title are removed from the menu. Any sub-items of the item that is removed are not removed from the menu. This will cause Wordpress to display them as top-level menu items.

For example, create a menu like this:

    - Test
    - (Empty title)
        - Sub item 1
        - Sub item 2
    - Test 2

It will be displayed like this:

    - Test
    - Sub item 1
    - Sub item 2
    - Test 2

If a menu item is removed, the sub-items should be removed too.

**Comment by johnclause** [comment]
Good point, thank you for the report. Is there any chance you would submit a pull request with a code to fix it?

**Comment by johnclause** [comment]
The fix will be in release 3.4.5, it is now on GitHub. Do you have a quick way to test it? Please, let me know if there is a problem.

**Comment by ouiliam** [comment]
this is still a problem on release 3.4.6.8 WP 4.8.1
add an empty custom menu item with # as URL (to be used as a submenu group title), and the order is messed up and changes to EN menu items are no longer properly mirrored in other languages.

when custom links are used, the custom link URL gets modified by qtranslate.

**Comment by ouiliam** [comment]
I found in your FAQ the solution to the custom link issue (&setlang=no) but the empty custom link menu items issue still remains.
