### ISSUE TITLE
How to user the_widget

### ISSUE THREAD

**Issue by nevoeiro** [qTranslate-Team/qtranslate-x#257]
Hi I would like to use the_widget('qTranslateXWidget', $args, $instance) but I don't know which vars I have to use on args and instance. Can you please show me an example.
I would like to use the selector and hide title and dots.
Thanks for help.

n

**Comment by qtranslateteam** [comment]
I updated FAQ with an example:
https://qtranslatexteam.wordpress.com/faq/#LanguageSwitchingMethods

Do you mind, after you figure it out, writing up a little tutorial, a few
phrases, which I could publish on FAQ page under question like "How do I
run the_widget( $widget, $instance, $args ) ?"

Thanks a lot,
John


On Fri, Sep 11, 2015 at 9:41 AM, nevoeiro <notifications@github.com> wrote:

> Hi I would like to use the_widget('qTranslateXWidget', $args, $instance)
> but I don't know which vars I have to use on args and instance. Can you
> please show me an example.
> I would like to use the selector and hide title and dots.
> Thanks for help.
>
> n
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/qTranslate-Team/qtranslate-x/issues/257>.
>



-- 
John Clause
qTranslate Team
https://qtranslatexteam.wordpress.com/about/
