### ISSUE TITLE
Build in use of load_textdomain()

### ISSUE THREAD

**Issue by shankiesan** [qTranslate-Team/qtranslate-x#258]
Hi qtranslate team,

Great work on the plugin. We love it.

Only one slight issue – the standard way of translating theme strings in WordPress is to put `.mo` files in the `wp-content/themes/{active-theme}/languages` directory.

This works well enough in WPML (which we're moving away from), but could be handled built-in in qTranslate. [this](http://boring-group.com/blog/2011/03/04/how-to-load-plugin-translation-mo-files-with-qtranslate/) article got me started, but something like this ended up working better for me:

`if ( function_exists('qtrans_getLanguage') ) { 
  $locale = get_locale();
  $mo_file = get_stylesheet_directory() . '/languages/' . $locale . '.mo';

  load_textdomain('mytextdomain', $mo_file);
}`

The only trick would be making it flexible to take any textdomain – perhaps this could be accomplished using a setting.

Let me know if you want a hand and I could integrate it here and do a pull request.

All the best,

Andrew

**Comment by johnclause** [comment]
Hi, @shankiesan:

Could you setup an example of a problem you are solving with step-by-step instructions? Preferably under one of the standard themes with minimum number of active plugins.

I am confused, why do you need to re-load the theme text domain? The plugin determines which language is active as early as possible in the function `qtranxf_init_language`, which runs in response to 'plugins_loaded' action at low priority.

Theme's textdomain is supposed to be loaded after this, in action `after_setup_theme`, and should pick up a correct language already detected and set in `qtranxf_init_language`. This is the original idea as far as I understood and it seems to work under the default standard WP themes, does not it?

Let us see why it is not working in your case. Maybe it is a theme, who needs to be corrected to load textdomain at right moment?

Here is some relevant WP documentation:
https://codex.wordpress.org/Function_Reference/load_plugin_textdomain
https://codex.wordpress.org/Function_Reference/load_theme_textdomain

Best regards,
John

**Comment by shankiesan** [comment]
Hi John,

My bad! You hit the nail on the head. My theme (which I'm developing, which I'm solely responsible for) didn't have load_theme_textdomain configured correctly! What an oaf.

Thanks for your comprehensive help.

Best wishes,

Andrew

**Comment by johnclause** [comment]
I am glad it works for you now!
Best Regards,
John
