### ISSUE TITLE
Allow setting PHP/Wordpress-Locale de_DE_formal

### ISSUE THREAD

**Issue by cornzy** [qTranslate-Team/qtranslate-x#262]
With wordpress 4.3 you have the ability to select the formal form of german language. The locale files (.mo) are installed as de_DE_formal. But in qtranslate-x language setup only 5 chars are allowed for the setting PHP/Wordpress-Locale.

**Comment by johnclause** [comment]
The latest version on [GitHub](https://github.com/qTranslate-Team/qtranslate-x) has the fix.
Thank you very much for the report.
