### ISSUE TITLE
Alternative for qTranslate Slug ?

### ISSUE THREAD

**Issue by daslicht** [qTranslate-Team/qtranslate-x#267]
Hello,
when I try to activate qTranslate Slug I get :

Qtranslate Slug:
This plugin requires at least WordPress 3.3 and either qTranslate-X (2.9 or newer), or mqTranslate (2.6.2.4 or newer), or qTranslate (2.5.8 or newer)

I have
qTranslate X Version 3.4.5.1
Wordpress 4.3.1
installed.

Is there any working alternative ? Or is there a way to translate slugs without plugins ?

**Comment by Grafcom** [comment]
@daslicht,
you used the qTranslate X version of GitHub right?
Check the plugin folder name, it must be - qtranslate-x -  and not - qtranslate-x-master -

**Comment by johnclause** [comment]
QTranslate Slug detects qTranslate-X presence by checking the folder name and expects "qranslate-x". You have to rename it to make QTranslate Slug work.

**Comment by daslicht** [comment]
I installed it via Wordpress and the folder name is: ***qtranslate-x***, 
so that s not the source of that error message.

**Comment by daslicht** [comment]
Thank you !
