### ISSUE TITLE
Undefined offset PHP notice on a clean install

### ISSUE THREAD

**Issue by ihorvorotnov** [qTranslate-Team/qtranslate-x#268]
Hi,
Just created a fresh install and got this PHP notice with WP_DEBUG enabled:
```
Undefined offset: 3 in /var/www/testsite/httpdocs/core/wp-admin/includes/class-wp-list-table.php on line 993
```
It says exactly about `wp-admin/includes/class-wp-list-table.php`, however, here's the stack and details reported by Query Monitor plugin:

![2015-09-21_19-13-44](https://cloud.githubusercontent.com/assets/1066083/9997464/f135bc54-6094-11e5-885f-e9445c5f4f1f.png)

It appears only on `wp-admin/options-general.php?page=qtranslate-x` page.

OS: Ubuntu 14.04 (staging) / Windows 10 (dev)
WordPress 4.3.1
qTranslate-X 3.4.4 (installed from WP.org repo)

P.S.: It also still has that old annoying PHP4 constructor issue, had to fix it manually in `qtranslate_widget.php:35`.

**Comment by johnclause** [comment]
This should be fixed in the latest at github. It would be great, if you
could test it on your server before we release it.

**Comment by ihorvorotnov** [comment]
@johnclause just tested master branch - no warnings or notices, including constructor issue. Thanks! Will stick with this version for now. Closing.

Any ETA for updates on .org?
