### ISSUE TITLE
Can't login to wp-admin

### ISSUE THREAD

**Issue by slavica90** [qTranslate-Team/qtranslate-x#270]
My site is down when this plugin is installed. I delete it and now the site is live but without css and I can't login to my wp-admin page. Every time I try it put language code to the URL.

My site is dragosh-stones.com

Thank you

**Comment by Grafcom** [comment]
@slavica90
to login use: http://dragosh-stones.com/wp-login.php?redirect_to=http%3A%2F%2Fdragosh-stones.com%2Fwp-admin%2F&reauth=1
Give more details about your installation.

**Comment by slavica90** [comment]
But when I try to login it is redirecting me to http://dragosh-stones.com/mk/...

**Comment by Grafcom** [comment]
After login try to remove in the URL mk/

**Comment by slavica90** [comment]
My problem is solved, I removed your plugin, I changed the home URL and site URL in database directly.
