### ISSUE TITLE
qtranxf_isAvailableIn() assumes post content is raw, but it is not

### ISSUE THREAD

**Issue by arildm** [qTranslate-Team/qtranslate-x#271]
`qtranxf_isAvailableIn()` loads a given post, and checks its content for a given language tag. But the loaded post is already translated to the current language (I think), so tags are never present and the function always returns `false`.

**Comment by johnclause** [comment]
Have you tried this under the latest version from [GitHub](https://github.com/qTranslate-Team/qtranslate-x)?

**Comment by arildm** [comment]
I tried with 4e295db, haven't tried with latest version yet.

I didn't find any usage either, other than my custom code which was designed for qTranslate (not X) some time ago.

**Comment by johnclause** [comment]
Ok, please, try the latest, there were some changes (in function qtranxf_postsFilter), which may affect this place. Also, it would be great if you could test the whole thing, all features that you use, not only this problem. This version has a few recent fixes and is about to be released.

**Comment by arildm** [comment]
Okay, thanks. I will, but not for a few days.

(To quickly (albeit unrelatedly) answer your request about general testing: I'm having problems right now with adding a "Custom link" to a menu. Suspecting it could be related to languages, but haven't looked into it yet. Will open a separate issue if so.)

**Comment by johnclause** [comment]
Right now, we need to make sure that the latest version at GitHub is no worse than the latest release at WP. We need to release the new version ASAP, as it has a few fixes people have been repeatedly reporting. For your new problem with "Custom link" to a menu, please, research if someone already reported it, or open a new separate issue. Thanks!

**Comment by arildm** [comment]
Tested with 3.4.5.2, same result.

**Comment by qtranslateteam** [comment]
Would you have time to find out which filter translates it?

**Comment by johnclause** [comment]
I updated this function qtranxf_isAvailableIn to fetch post_content from database, since get_post may return it both ways, translated or not depending on when it is run.

I am closing the issue, we may still write into closed issue, and we can reopen it if needed.

**Comment by arildm** [comment]
Oops, turns out I had some broken custom code that caused the problems I was having. Latest version 3.4.7 works well!
