### ISSUE TITLE
CMB2 integration for qTranslate-x

### ISSUE THREAD

**Issue by jmarceli** [qTranslate-Team/qtranslate-x#274]
Hey,
I would like to share info about my CMB2 qTranslate-x integration plugin. It doesn't support every possible CMB2 field but it might be useful for someone.

Here is the Github: https://github.com/jmarceli/integration-cmb2-qtranslate
and Wordpress.org: https://wordpress.org/plugins/integration-cmb2-qtranslate/

I hope I didn't "reinvent the wheel" (correct me if I'm wrong)

**Comment by johnclause** [comment]
Thank you very much, this is great. I do not see a wheel reinventing, it looks reasonable, although I am not familiar with CMB2 well enough. I updated page: https://qtranslatexteam.wordpress.com/integrated/ with your plugin. In case you are to write another integrating plugin, you may find it useful to read section "Plugins Naming Convention" in the above cited link.

Good luck to your plugin!

**Comment by jmarceli** [comment]
Thanks. I somehow missed naming conventions section while creating plugin.
