### ISSUE TITLE
Nirvana Theme - Language switcher not working in Top and Footer Navigation

### ISSUE THREAD

**Issue by bspica** [qTranslate-Team/qtranslate-x#280]
When added toTop Navigation and Footer Navigation Language switcher shows current language with no possibility to change it. In Primary Navigation works fine.

**Comment by Grafcom** [comment]
@bspica
can you give me a link to the site so I can see?

**Comment by bspica** [comment]
No, because it's not public yet.

**Comment by Grafcom** [comment]
This theme? https://wordpress.org/themes/nirvana/

**Comment by bspica** [comment]
Yes, that one.

**Comment by Grafcom** [comment]
It seems that these positions do not support drop-downs.
How many languages do you use?

**Comment by bspica** [comment]
Luckily, two. I changed Language Switcher URL to #qtransLangSw?type=AL and now I can choose alternative language from that location.
Thank you, you gave an idea! :)

**Comment by Grafcom** [comment]
You are welcome!
you can close this topic :-)
