### ISSUE TITLE
qTransxf not setting 'locale'?

### ISSUE THREAD

**Issue by shankiesan** [qTranslate-Team/qtranslate-x#281]
Hi qTranslate-Team,

Forgive me if this is operator error, but I've done quite a lot of testing and can't work out a solution so I'm beginning to think that it might be a bug.

I'm building a site for a client where I use [Event Organiser](http://wp-event-organiser.com) extensively. EO comes with pretty comprehensive gettext support; however, when using qTranslate, EO (and other other plugins, such as one that I've built) that rely on `get_locale()` to load their MO files don't appear to load translations.

EO loads its translations like this:

		function eventorganiser_pro_load_textdomain() {

			$domain = 'eventorganiserp';
			$locale = apply_filters( 'plugin_locale', get_locale(), $domain );

			$mofile = $domain . '-' . $locale . '.mo';

			/* Check the global language folder */
			$files = array( WP_LANG_DIR . '/event-organiser-pro/' . $mofile, WP_LANG_DIR . '/' . $mofile );
			foreach ( $files as $file ) {
				if ( file_exists( $file ) ) {
					return load_textdomain( $domain, $file );
				}
			}

			//If we got this far, fallback to the plug-in language folder.
			//We could use load_textdomain - but this avoids touching any more constants.
			load_plugin_textdomain( 'eventorganiserp', false, basename( dirname( __FILE__ ) ).'/languages' );
		}
		add_action( 'plugins_loaded', 'eventorganiser_pro_load_textdomain', 5 );

...which looks pretty good to me.

The problem is, if I go to a page that I have in Welsh on my site, `qtranxf_getLanguage()` returns `cy`, and `get_locale()` returns `en_GB` (my sites's default language). This means that none of my plugins can get the locale correctly.

Is this a bug or am I doing something wrong? If it's a bug, is it possible that including something like this might work? https://codex.wordpress.org/Plugin_API/Filter_Reference/locale

Cheers,

Andrew

**Comment by johnclause** [comment]
Locale is set in function `qtranxf_localeForCurrentLanguage`. Maybe you make your call before it was set?

**Comment by shankiesan** [comment]
That's a good line of investigation (as I was originally thinking that I could be hooking something incorrectly), but even in my theme template (when you'd expect everything to be fully set as it's rendering HTML) I get these results:

    qtranxf_getLanguage(); // outputs 'cy', as expected

    get_locale(); // outputs 'en_GB', the site's default language

Please feel free to tell me if this is more of a StackOverflow issue than an actual issue! :)

**Comment by johnclause** [comment]
I put line `	qtranxf_dbg_log('qtranxf_init_language: get_locale(): ',get_locale());` in a few places within function `qtranxf_init_language`, which is basically the first to be executed, the one which defines the active language, called on 'pugins_loaded' with priority 2, and after the line `require_once(dirname(__FILE__).'/qtranslate_hooks.php');` i shows the correct locale on my computer. Does it work the same on yours?

I hope this will help you to figure out how to time your calls. I am closing this issue for now to save the future clicks, we can still write into a closed issue, or we can re-open it, if needed. Thanks a lot.

**Comment by shankiesan** [comment]
Thanks for the tip on adding `qtransxf_dbg_log`.

I spent the morning testing and realised that all is good on my staging server and it's my local development environment that's to blame! What a drag. Sorry for the trouble and thanks for your time @johnclause
