### ISSUE TITLE
Saving bug after update

### ISSUE THREAD

**Issue by Tusko** [qTranslate-Team/qtranslate-x#284]
Hello. I'm using ACF Pro + ACF qTranslate + Qtranslate-X.
All plugins are latest version.

I have some bug with saving inside repeater
http://awesomescreenshot.com/03f5befp8e

**Comment by Tusko** [comment]
But on front-end all fine

**Comment by johnclause** [comment]
Not clear. Cannot reproduce. That field does not show color bar on the side, which means it is not multilingual. What exactly is a problem? Have you done initial troubleshooting: https://qtranslatexteam.wordpress.com/troubleshooting/

**Comment by Tusko** [comment]
`That field does not show color bar on the side, which means it is not multilingual` - what is color bar?
This field have lang switcher http://awesomescreenshot.com/00c5bj52a3

**Comment by qtranslateteam** [comment]
Then what is the "bug"? Please, follow the guidance
https://qtranslatexteam.wordpress.com/troubleshooting/ and provide clear
instruction how to reproduce the problem. Thank you.

**Comment by johnclause** [comment]
I hope you figured it out by now. I am closing this issue for now, due to the absence of the problem description, we can still write into a closed issue, or we can re-open it, if needed.

**Comment by Tusko** [comment]
bug was in ACF Qtranslate.
I'm sorry.

solution here https://github.com/fburatti/acf-qtranslate

**Comment by johnclause** [comment]
No need to "sorry", this is how the things get solved, I am glad you figured it out :+1:. Thank you for the report.
