### ISSUE TITLE
Echoing through jQuery

### ISSUE THREAD

**Issue by coldpumpkin** [qTranslate-Team/qtranslate-x#285]
Hello! There's a message that needs to be sent through jQuery, and I want to have that message displayed in several languages. I normally use PHP to display content in different languages like: ```<?php echo __("<!--:en-->pt<!--:--><!--:pt-->en<!--:-->"); ?>```

So I tried:
```
var meow = '<?php echo __("<!--:en-->en<!--:--><!--:pt-->pt<!--:-->"); ?>';
$('div').append('<p>' + meow + '</p>');
```

But it basically outputs ```enpt"); ?>```

Is there any way I can achieve this?

**Comment by johnclause** [comment]
Front end or admin? I do not see how it is related to jQuery. '<?php' gets executed in .php on the server. jQuery is executed in browser. In php file "<?php echo __("enpt"); ?>" will be replaced with the value of current language, at front end. On admin admin side, it will simply keep the same string, same as "<?php echo "enpt"; ?>" would do. These documents may help:
https://qtranslatexteam.wordpress.com/integration/.
https://qtranslatexteam.wordpress.com/multilingual-fields/

If you wish to extract the admin language in php from "enpt", you may use `apply_filters('translate_text','<!--:en-->en<!--:--><!--:pt-->pt<!--:-->');`, which will work on front end too.

Last observation, it is now more common to use square bracket encoding like this: "[:en]en[:pt]pt[:]".

I am closing this issue for now to save the future clicks, we can still write into a closed issue, or we can re-open it, if needed.

**Comment by coldpumpkin** [comment]
I understand what you're saying. I'm trying to achieve this in front end. To make myself clearer I want to output via jQuery certain translated text. So let's say, normally I'd do ```<!--:en-->en<!--:--><!--:pt-->pt<!--:-->")``` but if I output that via jQuery it will simply output ```enpt```all together. As in:

```
var meow = '<!--:en-->en<!--:--><!--:pt-->pt<!--:-->';
$('div').append('<p>' + meow + '</p>');
```

**Comment by johnclause** [comment]
So front end, php or java script? If language extraction has to happen in java script, not in php, then qtx does not use any script at front end. You may copy what is needed from /admin/js/common.js to your own script. But really, I do not understand why you would need that. The pieces of code you shown do not make sense to me so far.

**Comment by johnclause** [comment]
I still do not understand why you talk about java script if problem in the line "<?php echo __("enpt"); ?>", which is executed in php file. Print the output of `__()` to see what it is.

It just occurred to me, maybe you execute that line too early, before language and translation filters are set? Language extraction will only work after 'plugins_loaded' filter is executed.

**Comment by coldpumpkin** [comment]
The script is the last thing loaded in the website really. Yes, I'm trying to achieve this through javascript (jQuery library) as I said. Forget about the php tag, even with ```<!--:en-->en<!--:--><!--:pt-->pt<!--:-->``` it doesn't work. When sent through javascript, I mean.

**Comment by johnclause** [comment]
But you cannot use `__()` in java script, so what exactly are you doing and what exactly does not work for you? I gave you reference to `/admin/js/common.js` file where functions like `qtranxj_split` would give you hash table of translations, from which you may pick up the translation of language needed. But that script is loaded on admin side only. Can you describe the original task you are doing? Maybe there is a better way of doing what you are trying to do?

**Comment by coldpumpkin** [comment]
I'm not using ```__()``` anymore that's why I gave you the code I'm trying to use above, which is:

```
var meow = '<!--:en-->en<!--:--><!--:pt-->pt<!--:-->';
$('div').append('<p>' + meow + '</p>');
```

I'm not really an expert in this (either php nor javascript) that's why I came here to ask for help, maybe there's a way of doing this I'm not seeing. Basically what I'm doing above is defining a var with the content and then append it to a div when needed.

**Comment by johnclause** [comment]
I am sorry, at this place, we have community to discuss bugs, possible improvements, innovative ideas etc. You need some professional to help you. I gave you enough information to deal with your problem. A paid support is available via https://qtranslatexteam.wordpress.com/contact-us/. I am sure you'll figure it out one way or another, rather sooner than later, and I wish you all the best and good luck with your site. Thank you very much for understanding.
