### ISSUE TITLE
Support for DHVC forms

### ISSUE THREAD

**Issue by ventouris** [qTranslate-Team/qtranslate-x#287]
Any plan to add support for DHVC forms? Currently, the translation flags is there, but if you add a translation and call the form with the shortcode, then you have two forms on the page, regarding the language.

This is what I see on the front-end page. I can see the tags `[:en]` and `[:de]` and both forms.

[:en]
First form with the english content
[:de]
Second form with the german content
[:]

**Comment by Grafcom** [comment]
@ventouris
is it not easier to make two forms? For each language one.

**Comment by ventouris** [comment]
@Grafcom Maybe it would be easier to have a coffee first, then start working :P I spent a few hours fixing the issue of the above details and didn't think about creating two forms. Thank you

**Comment by Grafcom** [comment]
You are welcome! Now enjoy your coffee!
