### ISSUE TITLE
switching language not work in Divi using q-translate x

### ISSUE THREAD

**Issue by Finkensieper** [qTranslate-Team/qtranslate-x#293]
after preparing a hole english page in Divi everything works fine.
After preparing no other plugins installed.
Opening again to correct something every language switching didn't work???
If I try to edit a page or menu language is missing or menu change to englisch in german version...
Please help
www.house-intelligence.eu

**Comment by johnclause** [comment]
I already answered to your private e-mail. This is something very specific to your setup, please, continue in private.
