### ISSUE TITLE
Problems with cyrillic post_tags and categories v3.4.7 importing slugs

### ISSUE THREAD

**Issue by floopyzicer** [qTranslate-Team/qtranslate-x#308]
Ok so i finally made this to work, problem was on my side so after importing q-translate slugs(the import only gets post-slugs -----post_tags and category slugs are not imported. 

Also did the testing on post_names everything was fine just cyrillic post_names are shown by codes(same as sitemap show them) in sitemap there is no problem. 
So i did some test on some categories tried to translate slugs i translated 
en fr mk slug - on categories 
En slug stays
Fr slug stay(also not imported from q-translate slug
Mk slug vanish(i suspect cause it is cyrillic) but it worked with q-translate slug so it is doable i guess.

**Comment by johnclause** [comment]
Yes, we have already discovered this problem. Please, wait until we have a new version for testing. There is quite a few imperfections in the published one. Its further testing is pointless. I am going to remove that pre-release for now.
