### ISSUE TITLE
302 redirect on default language

### ISSUE THREAD

**Issue by ghost** [qTranslate-Team/qtranslate-x#309]
Hi!

I believe that I have found a bug.
The "qtranxf_init_language" method is performing a 302 redirect when I select the option: "Hide URL language information for default language.".

However, it would not be correct to add 301 as a parameter in wp_redirect?
Example: wp_redirect($target, 301) - line 81;

I say this for the sake of SEO.

http://example.com/default_lang/page.php ---> (302) http://example.com/page.php

Correct:

http://example.com/default_lang/page.php ---> (301) http://example.com/page.php

Can you could understand?

**Comment by johnclause** [comment]
Is this about one of these:

https://qtranslatexteam.wordpress.com/2015/02/26/browser-redirection-based-on-language/

https://github.com/qTranslate-Team/qtranslate-x/issues/306

The latter is a problem if you use caching plugin, the first one is "by design". Which one is your problem?
