### ISSUE TITLE
Change the version required

### ISSUE THREAD

**Issue by juanfran-granados** [qTranslate-Team/qtranslate-x#316]
First of all, thank you for keep on developing a terrific solution for multilang sites :)

Since you are requiring translation-install.php in **admin/qtx_update_gettext_db.php:26** and this file was included in version 4.0, you should upgrade the version required to 4.0 in your readme.txt.

Also, could you tell me which version is the newest that really requires 3.9?

Thanks!

**Comment by johnclause** [comment]
Thank you very much, I updated readme.txt. I do not know about 3.9. Try commenting out line which includes file qtx_update_gettext_db.php and see if it is ok? You will not lose much, just updates of gettext, which are now done by WP well enough as well. It only matters on the first install of a new language, and even that, you can also update translation needed manually via WP.

Why cannot you upgrade WP to the latest?

**Comment by juanfran-granados** [comment]
Thanks for your answer John! I will try your suggestion. We cannot upgrade to the latest version due to we are now in a really old version, and the Codex recommends not to upgrade more than 2 major versions in once. So, we are in our way :)

Thanks again.

**Comment by johnclause** [comment]
Just make a [test copy](https://qtranslatexteam.wordpress.com/how-to-site-test-copy/) and experiment as much as you wish ;) Most likely you will be fine, unless some other plugins or theme are also severely outdated, but it should not be too hard to fix.

I am closing this for now, we can still write into closed issue or we can re-open it if needed.
