### ISSUE TITLE
Mixes both languages on the page

### ISSUE THREAD

**Issue by filipavillar** [qTranslate-Team/qtranslate-x#320]
Hello
I Installed qtranslate on a wordpress theme - traveler developed by shinetheme. By default the pages are in UK, and i have translated them to PT . However some pages appear to be half in UK , half in PT. It is not assuming the same langue template.
see attachment
![pt _edit tour holiday active wordpress](https://cloud.githubusercontent.com/assets/16104571/11507942/4e0ce2fe-984e-11e5-858b-35840a7ad47a.png)
![pt templarios edit tour holiday active wordpress](https://cloud.githubusercontent.com/assets/16104571/11507958/61d1315a-984e-11e5-955a-66c8547cb6c5.png)

Your input would be much appreciated since i have no IT expertise

**Comment by johnclause** [comment]
Those fields are not multilingual: https://s.w.org/plugins/qtranslate-x/screenshot-1.png?r=1298571

Need [integration](https://qtranslatexteam.wordpress.com/integration/) or try using raw [multilingual](https://qtranslatexteam.wordpress.com/multilingual-fields/) values?

Please, use [Support Forum](http://qtranslate-x.com/support/) for "How To ..." questions, this place is for bugs and development.

FAQ and Startup Guide pages may also help:
https://qtranslatexteam.wordpress.com/faq/
https://qtranslatexteam.wordpress.com/startup-guide/
