### ISSUE TITLE
Slug on default language menu

### ISSUE THREAD

**Issue by xDiglett** [qTranslate-Team/qtranslate-x#323]
The default language on my site is NL, when changing to EN through the language changer menu it shows the default slug again **/nl/** in the menu instead of hiding it.

![Redirect](http://i.imgur.com/hpinzqP.png)

Then when you visited it, it does a 302 redirect to the page without slug.

**Comment by Grafcom** [comment]
@xDiglett
Visit the new <a href="http://www.qtranslate-x.com/support/">Support Forum</a>
