### ISSUE TITLE
Language settings page is empty

### ISSUE THREAD

**Issue by essensx** [qTranslate-Team/qtranslate-x#330]
Console reports there is an issue with uniqueId. jQuery(...).uniqueId is not a function

**Comment by adrienlamotte** [comment]
Hi, same problem here

**Comment by johnclause** [comment]
Do you keep observing this in the latest release? I am closing this issue for now, hoping that it is resolved, we can still write into a closed issue, or we can re-open it, if needed.

**Comment by adrienlamotte** [comment]
After I've deleted and reinstall the plugin (with the same version), the problem disappeared... 
Thx anyway

**Comment by johnclause** [comment]
I am glad it is solved. You could probably simply deactivate/activate this plugin, read bold text here: https://qtranslatexteam.wordpress.com/2016/04/23/release-notes-3-4-6-5/

**Comment by epiclight** [comment]
Hi, have same issue
