### ISSUE TITLE
Better shortcode name for Ukrainiane language according to WP standarts

### ISSUE THREAD

**Issue by okrasn** [qTranslate-Team/qtranslate-x#335]
Find difficult's of using shortcodes in theme like `<!--:en-->` cause not standart name for ukrainian language. According to this https://translate.wordpress.org/locale/uk ukrainian lang shortcode must be `<!--:uk-->` and not `<!--:ua-->`. More ( https://github.com/qTranslate-Team/qtranslate-x/blob/master/qtranslate_options.php#L187 )

p.s. In case of any I can create pull request with fix of problem, but need add appropriate message for users that using plugin with broken locale name now

**Comment by johnclause** [comment]
Hi @okrasn, we can put both, in order not to break existent installations. Thanks a lot for the suggestion. I am not sure how 'ua' got there, must be a "history" by now. There is a [PR ](https://github.com/qTranslate-Team/qtranslate-x/pull/401), with uk translation. Please, consider getting in touch with the author to share the translation work :+1: and to improve the translations, they are apparently still working on it.

**Comment by johnclause** [comment]
Done: https://github.com/qTranslate-Team/qtranslate-x/commit/1a34d820fbaac61accae78c820bd87e2b59997b9
