### ISSUE TITLE
ACF v5 and qtranslate x - custom class names only affect first field

### ISSUE THREAD

**Issue by alancwoo** [qTranslate-Team/qtranslate-x#34]
Regarding [this discussion](https://wordpress.org/support/topic/cant-get-acf-to-work-with-qtranslate-x?replies=11#post-6610798) on the Wordpress forums.

Language toggle only affects the first field with a custom class defined.

**Comment by johnclause** [comment]
Hi Alan, please, discuss the ACF integration issues with the author of the new plugin https://wordpress.org/plugins/acf-qtranslate/, who has just made it compatible with -X: https://github.com/qTranslate-Team/qtranslate-x/pull/40
