### ISSUE TITLE
Term edit page has no Language buttons in wp 4.5-alpha-35776

### ISSUE THREAD

**Issue by LC43** [qTranslate-Team/qtranslate-x#342]
Hi, its me again :)

this a nightly build, but i just wanted to warn that I think 4.5 will break this form.

thanks!

**Comment by johnclause** [comment]
Thank you very much, Pedro, sorry it took so long to catch up with this.Next release will have the [fix](https://github.com/qTranslate-Team/qtranslate-x/commit/f8149ca01f0f39da0cabe4a3e677449b29565877).

**Comment by LC43** [comment]
thank you for fixing and making qtx a great plugin again! :100:
