### ISSUE TITLE
Default language didn't work when "Hide URL language information for default language" is checked

### ISSUE THREAD

**Issue by ghost** [qTranslate-Team/qtranslate-x#349]
Hi, i use latest WordPress & (latest official wordpress plugin directory) of qTranslate-X.

Example: there are __en, fr, ru__. The default is __en__. But, when _Hide URL language information for default language_ is checked, the default language url doesn't work. It always stay in the same page & url.

Example:
from: http://example.com/fr/about/
click link or enter url to: http://example.com/about/ (didn't use **en** because the option is checked)
result: http://example.com/fr/about/ (stay in the same page, same url)

I have no idea about what causes this problem. Then i tried downloading the latest version from GitHub and the result even worse (the setting screen totally didn't work). So, i stay with the official version of qTranslate-X.

**Comment by chiflon** [comment]
Same problem here!
Moreover, in lang switcher default **/en** appears in the slug when it shouldn't

**Comment by johnclause** [comment]
Please, read the comment on #370
