### ISSUE TITLE
qTranslate doesn't use any .po and .mo files but it's own

### ISSUE THREAD

**Issue by dev-masta** [qTranslate-Team/qtranslate-x#351]
I've reading and trying to solve this whole day.
I've used qTranslate couple of years back and would love to use this plugin, but I just can't get it to work.

I have just tried to create a clean installation of wordpress, didn't change any options (like, permalinks) at all, didn't install any plugin, or messed with the theme, the installation can't be cleaner.

I have changed the default language in Setting / General and activated the plugin.
Then I have deleted the German language and installed Hrvatski (hr)

But the plugin doesn't work.

It translates some word in the backend (and hello world post's title and content), but it won't use the .mo files of either wordpress or the theme.
If I deactivate the plugin, wordpress works normally in both english and hrvatski.

**Comment by Grafcom** [comment]
@dev-masta
check Settings - Languages - Edit language - change Locale from hr_HR to hr
See also here https://make.wordpress.org/polyglots/teams/
More questions? Visit the qTranslate Support Forum at http://qtranslate-x.com/support/

**Comment by dev-masta** [comment]
@Grafcom 
Thank you, indeed, that solved the issue I was having!

I hope you will include the change in the installation, because Croatian (Hrvatski) is one of the predefined languages in your plugin and that is why I didn't think about editing the language settings.
