### ISSUE TITLE
Language Menu has a strange html output

### ISSUE THREAD

**Issue by 72quadrat** [qTranslate-Team/qtranslate-x#36]
The language menu prints a-tags without href, the image flags have no alt attribute and the li-tags have no classes what language ist currently chosen or such. This makes it really difficult to style the language-menu

**Comment by 72quadrat** [comment]
I could hide the links without any href with css but of course that's not valid html – or is it?

	a { display: none; }
	a[href]{
		display: inline-block;
		@extend .btn;
	}

**Comment by mweimerskirch** [comment]
I suppose you mean the language menu in the widget? Could you post a screenshot? The alt-attribute is indeed missing, but I can't find any missing href-attributes and there has to be a class "active" on the "li" for the active language.

**Comment by johnclause** [comment]
@72quadrat: the latest from GitHub https://github.com/qTranslate-Team/qtranslate-x/archive/master.zip, has alt attribute. Please, let us know if the other problem goes away too, since I cannot reproduce that one in any way.

**Comment by johnclause** [comment]
@72quadrat, please re-submit this issue with a clarification, as Michel suggested, if there is still a problem under the latest version on github.
