### ISSUE TITLE
Admin language not working

### ISSUE THREAD

**Issue by valonia14** [qTranslate-Team/qtranslate-x#365]
Hi! I have installed this plugin for finnish site. After installation, default language is English in admin, and I can't change it. When I go to admin > Settings > General and choose Finnish to default language, site is refreshed after saving but language not changed. Finnish is installed to plugin languges. When I deactivate plugin, finnish is working again in admin.

**Comment by johnclause** [comment]
It is in Startup Guide: https://qtranslatexteam.wordpress.com/startup-guide/#HowToSwtchAdminLanguage:

>To switch an admin language use the language menu in the top right corner of the admin screen.
