### ISSUE TITLE
make "For the sake of viewer convenience ..." strings translatable from admin backend

### ISSUE THREAD

**Issue by gromper** [qTranslate-Team/qtranslate-x#368]
Hi,
it's great that you can change the "Sorry, this entry is only available in %LANG:, : and %." line right in the settings of qtranslate-x. However, the fact that the following two sentences can only be translated via gettext makes this quite useless, as you don't want to have two languages in a paragraph.
Would it be possible to add translation possibility for these two lines to the settings panel?

![qtranslatex](https://cloud.githubusercontent.com/assets/18070768/14045666/5c77426e-f29c-11e5-92c2-e1d91c00f013.png)

**Comment by johnclause** [comment]
It is translatable via .po file. It may not yet be translated in your language.

I am closing this issue for now to save the future clicks, we can still write into a closed issue, or we can re-open it, if needed.
