### ISSUE TITLE
DB Conversion to Brackets / Legacy throws errors because of mysql_real_escape_string, better use $wpdb->prepare 

### ISSUE THREAD

**Issue by kuchenundkakao** [qTranslate-Team/qtranslate-x#37]
As the title says, if you try to use the "convert database" function, you get a lot of errors because no mysql connection is opened.

Please replace lines 81 and 97 in the admin/admin_utils.php with the following:

    $wpdb->query($wpdb->prepare('UPDATE '.$wpdb->posts.' set post_content = %s, post_title=%s, post_excerpt=%s  WHERE ID=%d',$content, $title, $excerpt, $post->ID));

http://codex.wordpress.org/Data_Validation#Database

**Comment by mweimerskirch** [comment]
@kuchenundkakao you can edit the file right here on GitHub by clicking on the small pencil in the top right corner of the file and follow the messages on screen to create a "pull request". This way, your fix will get integrated much faster.

**Comment by kuchenundkakao** [comment]
Thanks, done that ;)

**Comment by mweimerskirch** [comment]
This can be closed. Fixed by #48
