### ISSUE TITLE
Deprecated feature PHP7 error

### ISSUE THREAD

**Issue by growdigital** [qTranslate-Team/qtranslate-x#371]
I'd like to use qtranslate-x but I'm getting this error when activating the plugin:
> methods with the same name as their class will not be constructors in a future version of PHP qtranslate

I'm using the [Trellis stack](https://roots.io/trellis/) which I guess is using PHP7, hence the error message. 

Any easy workarounds? I don't really want to start hacking the plugin code.

**Comment by johnclause** [comment]
Duplicate of https://github.com/qTranslate-Team/qtranslate-x/issues/359

**Comment by growdigital** [comment]
thanks for link, sorry not to reply sooner, didn't get notification!
