### ISSUE TITLE
German language file uses 'Amerikanisches Englisch' as display name for locale 'en'

### ISSUE THREAD

**Issue by BjoernKW** [qTranslate-Team/qtranslate-x#375]
It should be just 'Englisch' for locale 'en'. 'Amerikanisches Englisch' should just apply to 'en_US'.

**Comment by johnclause** [comment]
Looks like this is how it is: https://github.com/qTranslate-Team/qtranslate-x/blob/v3.4.6.7/lang/language-names/language-de_DE.po#L8 ?

I am closing this issue for now to save the future clicks, we can still write into a closed issue, or we can re-open it, if needed.

**Comment by BjoernKW** [comment]
The problem is my language setting is "en", so according to this language file it should display "Englisch".  However, "Amerikanisches Englisch" is shown.

**Comment by BjoernKW** [comment]
Sorry, my bad. Wrong locale setting.
