### ISSUE TITLE
Portfolio crumbtrails display all languages

### ISSUE THREAD

**Issue by paoPuscher** [qTranslate-Team/qtranslate-x#376]
Hi, I've just installed the  plugin,  have already uploaded some translated content. Everything seems fine, but the portfolio navigation (crumbtrails)  display all the the portfolio titles in every language....
![crumbtrails](https://cloud.githubusercontent.com/assets/18504269/14582872/13b1f868-0411-11e6-96e5-60df672141b9.jpg)  what can I do?

**Comment by paoPuscher** [comment]
the site is http://laubadia.com/fr/portfolio/mantenimiento-de-instalaciones/

**Comment by johnclause** [comment]
We are already in private communication. Please, when submit a duplicate, provide links to other places with the same issue: https://wordpress.org/support/topic/read-me-first-use-dedicated-support-forum-for-qtranslate-x
