### ISSUE TITLE
Widget "About me" is not being translated

### ISSUE THREAD

**Issue by mariiguedes** [qTranslate-Team/qtranslate-x#379]
Hi guys! Has anyone had this same problem?
The plugin works great in the whole site, but I have an "about me" widget and even though I see the button for the different languages, when I change the text in one language, it automatically changes in the other.
Can you help me please?

My site is: www.bus142.com.br
WordPress 4.5, theme Redwood.

Thanks a lot!

**Comment by johnclause** [comment]
I am not familia with that widget, but apparently it needs [Integration](https://qtranslatexteam.wordpress.com/integration/) or use raw [multilingual](https://qtranslatexteam.wordpress.com/multilingual-fields/) entries.
I am closing this issue as "How To", which should not be here, we may still write into it or we may reopen it, if needed. For "HowTo" issues use [Support Forum](http://qtranslate-x.com/support/).

**Comment by mariiguedes** [comment]
Thanks for the answer, @johnclause. I think the problem might be with integration... will try to find out what to do.
