### ISSUE TITLE
qTranslate does not hide menu items for untranslated content in WP4.5

### ISSUE THREAD

**Issue by mwijngaard** [qTranslate-Team/qtranslate-x#382]
Since an update to wordpress 4.5, qTranslate does not seem to be hiding the menu items for untranslated content anymore. I've tried resetting and reinstalling the plugin, but this keeps coming back. The post content itself is still correctly hidden. Perhaps this is related to the WP4.5 menu update mentioned in 9a621fa0fd5a8577ce317a219e06b1437df9c600?

**Comment by mwijngaard** [comment]
I can confirm that this has been fixed after updating to 3.4.6.7, great work!

**Comment by johnclause** [comment]
I am glad. I wish all issues would close this way ;) Thanks a lot.
