### ISSUE TITLE
Missing argument 2 for qtranxf_add_meta_box_LSB() in ... - on plugin "Maintenance" page

### ISSUE THREAD

**Issue by miroslawlis** [qTranslate-Team/qtranslate-x#389]
Hello.
I got this error on settings page ("Maintenance" plugin)
`Missing` argument 2 for qtranxf_add_meta_box_LSB() in `...home/wp-content/plugins/qtranslate-x/admin/qtx_admin_utils.php`

Plugin [https://wordpress.org/plugins/maintenance/]

Fresh WP installation.

**Comment by johnclause** [comment]
Which theme?

qtranxf_add_meta_box_LSB is supposed to have 2 arguments:
https://codex.wordpress.org/Plugin_API/Action_Reference/add_meta_boxes

It must be an overlook in your theme or one of the plugins.

Anyway I added default value for the second argument, just to mute such message in the future.

Thank you very much for the report.

**Comment by miroslawlis** [comment]
Storefront (default woocommerce)

Thx for patch :+1: 

Cheers

**Comment by johnclause** [comment]
Strange, that is what we use routinely for testing, but never saw that message. Anyway ...
Thanks!
