### ISSUE TITLE
No possible bulk update with woocommerce

### ISSUE THREAD

**Issue by wocmultimedia** [qTranslate-Team/qtranslate-x#390]
Hi John,
I have the needs of making several bulk changes in the product price but the bulk Edit option doesn't work with woocommerce. If I go to Product list, select some products, go to bulk > Edit, it opens regularly and shows tab to be handled but after making the changes needed and press update the page refreshes. It appears x products updated but actually the products details are not changed at all.

Any suggestion? You have the admin credential to access and check http://www.wocmultimedia.biz/test_site/
Thanks 
Angelo

**Comment by johnclause** [comment]
Does it work with qtx off? If it does, please give a specific example to reproduce.

**Comment by wocmultimedia** [comment]
Hi
I apologize for my report but it doesn't work also with qtx off. I forgot to make the check before write here. Thanks. Angelo

**Comment by johnclause** [comment]
Good, I can only wish all would get resolved that easy :+1:
