### ISSUE TITLE
date_i18n not working when qTranslate-X is activated

### ISSUE THREAD

**Issue by tophattom** [qTranslate-Team/qtranslate-x#391]
I'm using a plugin that uses Wordpress' date_i18n function to resolve day names. However when qTranslate-X is activated dates are only displayed in English. When I deactivate qTranslate-X everything seems to work just fine.

Also, while qTranslate-X is activated the admin panel is always in English regardless of what is selected in the language chooser in the top-right corner. 'Settings -> General -> Site language' also always resets to English when I try to change it.

**Comment by johnclause** [comment]
About swiching language, read [Startup Guide](https://qtranslatexteam.wordpress.com/startup-guide/).
About date_i18n, play with option "Date / Time Conversion" on page `/wp-admin/options-general.php?page=qtranslate-x#advanced`

**Comment by tophattom** [comment]
Thanks! Everything is working just fine now.
