### ISSUE TITLE
Editor growing on key press or click inside editor in "visual" tab

### ISSUE THREAD

**Issue by nr1q** [qTranslate-Team/qtranslate-x#393]
Since I installed this plugin (like 3 o 4 weeks ago) I got an issue with the height of the editor in _visual_ mode. The bug is that by typing inside the editor or just with a single click on it, the `iframe#content_ifr` element grows by 2 pixels on each action.

Is not that critical because switching to _html_ tab and back again to _visual_, the height gets reset. But is non comfortable for my client.

**Comment by johnclause** [comment]
I could not reproduce it under a standard theme. Which theme is it under? Or which plugin is in conflict?

**Comment by nr1q** [comment]
I disabled all plugins but the bug remains. For the theme I'm using https://github.com/studiorabota/sage-twig-theme Though not using any scripts for the WP admin side.

**Comment by johnclause** [comment]
Can you reproduce it under a standard theme like Twenty Sixteen? If not, then I guess, contact the theme with this issue?

**Comment by nr1q** [comment]
Yeah, I just tested with the default themes and doesn't happen that bug. So I'll contact the theme author. Thanks for that great plugin, once I get my paypal account recovered I'll do my donation. :)

**Comment by johnclause** [comment]
Thanks!
