### ISSUE TITLE
language tag displayed as full text with brackets

### ISSUE THREAD

**Issue by DennysDionigi** [qTranslate-Team/qtranslate-x#394]
Hello, in this website I installed this plugin and updated to the latest version, but I really don't know why the portfolio categories title are displayed with the square brackets in both languages, as **full text**.

You can see this bug on the right and left sides of the page http://goo.gl/YdxNs4

I also installed qtranslate slug for the full compatibily but when I added the 2 permalinks languages, nothing happens, so I deleted it. But I'm still stuck in this problem.

Is there any code should I add? My MENU is displayed correctly in both languages.
The language atteibute is setted with the main language  (IT) and the second one (EN) as final path.

**Thanks for any help**

**Comment by johnclause** [comment]
Sounds like you need [integration](https://qtranslatexteam.wordpress.com/integration/), which you can do yourselves, or you can hire a PHP developer, we are also available for hire: https://qtranslatexteam.wordpress.com/contact-us/
Thank you.
