### ISSUE TITLE
can't delete item from repeater

### ISSUE THREAD

**Issue by oresh** [qTranslate-Team/qtranslate-x#406]
When I try to delete an item from ACF repeater, it can't find the element and gives an error.
https://www.dropbox.com/s/z75id7k6pc6ghwo/%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82%202016-07-18%2019.16.27.png?dl=0
https://www.dropbox.com/s/m1yzuepifdm13pe/%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82%202016-07-18%2019.17.19.png?dl=0

File `acf-qtranslate/assets/acf_5/qtranslatex.js`
The error is here:

> acf.fields.repeater.remove = function(event) {
>   var row = event.$el.closest('.acf-row');
> ...

The quick fix would be:

> acf.fields.repeater.remove = function(event) { 
>   var $el = (typeof event.$el !== 'undefined') ? event.$el : event;
>   var row = $el.closest('.acf-row');
> ...

**Comment by johnclause** [comment]
Please, report it to ACF-qTranslate, we do not control their code. Thanks!

**Comment by oresh** [comment]
got it, thanks!
