### ISSUE TITLE
Warning in admin page when debug is active

### ISSUE THREAD

**Issue by wocmultimedia** [qTranslate-Team/qtranslate-x#408]
Hi John,
please review this new warning appearing on my admin page of the test-site you already used which has debug on.
Warning: Cannot modify header information - headers already sent by (output started at /web/htdocs/www.wocmultimedia.biz/home/test_site/wp-admin/includes/upgrade.php:2225) in/web/htdocs/www.wocmultimedia.biz/home/test_site/wp-content/plugins/qtranslate-x/qtranslate_core.php on line 388

Hi have installed latest WP version.
Thanks for helping understanding it's meaning and maybe fix it.
Angelo

**Comment by johnclause** [comment]
How do I reproduce it? It may not be qtx at fault. There must be a message output before this one, which reports an actual error. That error is reported early enough, before headers are finalized, which causes this message from qtx. Look for that other error to see the actual reason.

**Comment by wocmultimedia** [comment]
John please, enter admin area to the site http://www.wocmultimedia.biz/test_site/ you have the access data and check because there's no other message or at least i don't understand where to look for.
 If lost access data just tell me I will send to your email

**Comment by johnclause** [comment]
I did enter admin area, I did not see an error. Look through the page source (Ctrl+U). The error message must be in the beginning, since it must have come before headers.

**Comment by johnclause** [comment]
Problem disappeared. It could have been right after update of some plugin, who sent a one-time error message - it is kind of normal ... can happen. You may probably look it up in error_log.
