### ISSUE TITLE
get_the_excerpt() not working properly in translated page

### ISSUE THREAD

**Issue by wjmisc** [qTranslate-Team/qtranslate-x#41]
The number of characters are trimmed accordingly at default EN page .
However, when I navigate to ZH page. The number of characters are trimmed wrongly with  get_the_excerpt();

**Comment by mweimerskirch** [comment]
I wasn't able to reproduce this. Are you using any other plugins that modify the content? Do you have the same problem when you disable the other plugins?
I suppose this is a multibyte issue (meaning that characters that are 2 or more bytes long get counted incorrectly), but I couldn't find anything in the qtranslate-x code that would cause this.

**Comment by wjmisc** [comment]
Dear Michel

Apologies. Upon further research, I realised that the issue does not lie
with your plugin.
