### ISSUE TITLE
Language menu broken html

### ISSUE THREAD

**Issue by kodinvis** [qTranslate-Team/qtranslate-x#410]
Hello! I've installed the plugin and turn on language menu:
http://i.imgur.com/buopMVH.png

But on the site I see broken html:
http://i.imgur.com/GH1leGb.png

Could you fix it please?

**Comment by johnclause** [comment]
Some themes do not allow pics in menu, probably unintentionally, they simply did not test it. Show them how it works under a standard theme like Twenty Sixteen and ask them to make it work in a similar way. 

I think you may simply put any `<img>` tag into the Navigation Label  of any menu item, and it will probably not show up either, does not it? This way would be easier to talk to theme, without giving them a chance to blame all to qtx.

If you wish our help to fix their code, please, submit a [request for a paid job](https://qtranslatexteam.wordpress.com/contact-us/).

Thanks!
