### ISSUE TITLE
Hide Flag for the current Language

### ISSUE THREAD

**Issue by sobreira** [qTranslate-Team/qtranslate-x#426]
Hi guys, 
Is here a way to hide the flagfor the current language selected.

Example:
Website with **pt-br** and **en-us**,
When I´m in **pt-br** only show up **en-us** flag and vice versa.

Thanks a lot!

Edson

**Comment by adeacetis** [comment]
Hello @sobreira,

I'm a bit late at the game, but here's what a found. 

The documentation has a quite comprehensive explanation on how to configure the Language Switcher Menu — assuming you've chosen this method of integration: 
https://qtranslatexteam.wordpress.com/faq/#LanguageSwitcherMenuConfig
"Flags" is the attribute you wants to edit.

Keep us informed on your progress.

Cheers,

**Comment by sobreira** [comment]
Thanks!
