### ISSUE TITLE
Convert multisites to qtranslate-x

### ISSUE THREAD

**Issue by Tusko** [qTranslate-Team/qtranslate-x#428]
hello guys!
I have a website, which has translations on multidomains, using wordpress network + plugin `WordPress MU Domain Mapping`.
Can anyone help with converting multisites to single site with qtranslate-x or have any ideas/issues?

**Comment by adeacetis** [comment]
Hello Tusko, 

Are you looking to expand this plugin's functionality or to fix a bug ? 
Have you already tested QTranslate-X on multisite ? Is it working ? Have you experienced issues ?

I haven't tested it personnaly but it looks like the team was working on some url issues related to multisite. You might have hit a edge case they didn't foresee at the time. 

See [#228](https://github.com/qTranslate-Team/qtranslate-x/issues/228) and [#243](https://github.com/qTranslate-Team/qtranslate-x/pull/243)

Maybe can you be a bit more canonical on what you're trying to achieve.

Cheers.

**Comment by Tusko** [comment]
@adeacetis no, this is not a bug.
I have multisite without qtranslate-x (each site is in diffirent language). 
Now I need only one site with multilanguages, with using qtranslate-x, not multisites

**Comment by adeacetis** [comment]
Well you just have to start the implemenation. At the time of writing, I'm not sure whether there's a way to automate that. 
I'm afraid you'll have to insert the content manually unless someone has a better solution.

Have you tried to set the plugin up ?
