### ISSUE TITLE
Widget 'qTranslate Language Chooser' not translated

### ISSUE THREAD

**Issue by pedro-mendonca** [qTranslate-Team/qtranslate-x#43]
The widget is not getting language files, shows english text.

**Comment by mweimerskirch** [comment]
You can add translations for your language file by modifying the ".po" file for your language right here on GitHub: https://github.com/qTranslate-Team/qtranslate-x/tree/master/lang

**Comment by pedro-mendonca** [comment]
Hi, I'm translating this plugin for a while now in portuguese (pt_PT), everything is translated but the text in the widget.
I think qtranslate_widget.php isn't getting the textdomain somehow.
