### ISSUE TITLE
Undefine function

### ISSUE THREAD

**Issue by realtebo** [qTranslate-Team/qtranslate-x#430]
> Fatal error: Call to undefined function wp_normalize_path() in /htdocs/public/www/wp-content/plugins/qtranslate-x/qtranslate_utils.php on line 72

I suggest to simply add the following code at the end of `qtranslate-x/qtranslate_compatibility.php`

```
if(!function_exists('wp_normalize_path')){
    function wp_normalize_path( $path ) {
        $path = str_replace( '\\', '/', $path );
        $path = preg_replace( '|(?<=.)/+|', '/', $path );
        if ( ':' === substr( $path, 1, 1 ) ) {
            $path = ucfirst( $path );
        }
        return $path;
    }
}
```

Without this, when enabling plugin it crashed because this wp function was added after 4.x release.

Please, integrate this into your codebase to maintain 3.6.1 compatibility as stated

I created the [Pull Rquest 431](https://github.com/qTranslate-Team/qtranslate-x/pull/431)

**Comment by adeacetis** [comment]
Hello, 
I am not sure about best practice on code compatibility but this solution looks quite simple to implement. I'd go for it too. 

However, there are a couple of typos in your comment which is also a bit inaccurate. The function "wp_normalize()" has been introduced in WordPress version 3.9.0, therefore your patch fixes the incompatibility — at least in regard of this function — with any WordPress installation of version 3.8.X and under.

I would enhance your comment that way: 
From : "To keep comptible with 3.6.1 version where this function doesn't exists"

To : "To keep the plugin _compatible_ with WordPress version 3.8.3 and under where this function doesn't _exist_. "

What do you think ?

Cheers,

**Comment by realtebo** [comment]
Hi !
Of course, I cannot do nothing else that fully approve your precisations, because your're more experienced than me both on WP and in this excellent blugin. I'm a old PHP coder, but I'm a newbie in WP world..

Feel free to implement or not this suggestion, and to modify my original post.
thanks for your work
