### ISSUE TITLE
Website constantly redirecting (I want to cry)

### ISSUE THREAD

**Issue by Abdel4** [qTranslate-Team/qtranslate-x#464]
I had installed and activated this plugin because I've used it before and had a great experience. This time round though, things have gone pear shape! After selecting the languages I wanted to translate and started translating, I realized that as soon as I change language on the switcher, I get a CSSless website and when I try to go back to the default language, it constantly redirects to ES or DE site depending on how its feeling and the error console is showing this:

unreachable code after return statement ajs.js:80:12
unreachable code after return statement ajs.js:80:12

I'm using my hosting companies recommended .htaccess which could be one of the issues I've read. If I have missed any important info, please let me know.

P.S. This is the first time I post on here, so take it easy on me! I know some of you get pissed off when its formatted incorrectly.

Thanks in advance

A.

**Comment by adeacetis** [comment]
Hello @Abdel4,
I have no idea what could be the reason of this behaviour. 
Do you have a live url to provide ?
Cheers
