### ISSUE TITLE
 TypeError: Cannot read property 'getNode' of undefined

### ISSUE THREAD

**Issue by simplicitylab** [qTranslate-Team/qtranslate-x#47]
Hi,

Platform info: 

- OSX - Chrome 40.0.2214.111 (64-bit)
- On Firefox I couldn't reproduce it

Problem:

On a clean install + qtranslate-x I get the following error when editing a post (that has the visual tab active on load)

Uncaught TypeError: Cannot read property 'getNode' of undefined 

Steps to reproduce:

1) Install wordpress 
2) Install qtranslate-x and enable it
3) Post > edit "Hello world" for example

This bug only occurs when "Visual tab" is the active one on load. If for example "Text" and I switch to "Visual" there is no error. 

I have the feeling that it is trying to access an element in the DOM that at that point isn't loaded/ready yet. I need to find some time to investigate further.

**Comment by johnclause** [comment]
I currently do not have OSX to try to reproduce it. Are you  developer? Would you mind trying to locate the problem?

**Comment by johnclause** [comment]
Is this still a problem in the latest version from github, for example, https://github.com/qTranslate-Team/qtranslate-x/archive/3.2.9.8.3.zip?

**Comment by simplicitylab** [comment]
Hi,

Sorry for not responding. We had a death in the family and I only started working today (and to make matters worse on another project) If I find some time, I will try to test it!

**Comment by simplicitylab** [comment]
Hi,

Found some time to test it and it seems to be fixed.

1) Install wordpress 
2) Install qtranslate-x and enable it
3) Post > edit "Hello world" for example

No more error 

OSX - Chrome Version 41.0.2272.118 (64-bit)

**Comment by johnclause** [comment]
Thanks for testing it out!
