### ISSUE TITLE
NO Support in a long time Is this Dead ? 

### ISSUE THREAD

**Issue by raykai** [qTranslate-Team/qtranslate-x#470]
NO Support in a long time Is this project dead ? 

it seams like il need to go with WPML....

no support since Jun 23

i dont want to go with WPML but there are some buges that need fixing.

**Comment by VaLeXaR** [comment]
I also interested in this issue. qTranslate-X is excellent plugin. And easier to use than WMPL. Easy to integrate with other plugins.

**Comment by The3IC** [comment]
Indeed, qTranslate is nice, but the number of problems is getting out of hand.

**Comment by raykai** [comment]
see this post from the Plugin Author John Clause: https://wordpress.org/support/topic/what-is-the-future-of-qtranslate-x/

**Comment by adeacetis** [comment]
No, please see this issue.
https://github.com/qTranslate-Team/qtranslate-x/issues/476

**Comment by johnclause** [comment]
Duplicate of https://github.com/qTranslate-Team/qtranslate-x/issues/476
