### ISSUE TITLE
qtranslate-x & Yoast sitemaps not working

### ISSUE THREAD

**Issue by rolka** [qTranslate-Team/qtranslate-x#481]
Hi,

Does anyone have a problem with Yoast's sitemaps? I'm using latest qtranslate-x and latest Yoast SEO plug in, I get a 404 error when I click on a link to open a site map.

Thanks

**Comment by rolka** [comment]
No one?

**Comment by rolka** [comment]
come on, don't be shy :)

**Comment by floopyzicer** [comment]
The problem is not in q-translate or yoast if you have WP super cache plugin turn it off and your sitemaps will probably start working, i experienced this after last wordpress update .

**Comment by rolka** [comment]
@floopyzicer no, no luck after I disabled WP Super Cache, any other ideas? :)

**Comment by rolka** [comment]
Ha!!! And one month later I found that it was this bad boy: https://wordpress.org/plugins/query-monitor/
