### ISSUE TITLE
"qTranslate META" integration

### ISSUE THREAD

**Issue by nkint** [qTranslate-Team/qtranslate-x#53]
Hi, 
I was using qTranslate but due to deprecation I'm happy to go on with qTranslate X.

For my websites I was using qTranslate META:

__Multilingual support for META tags. Requires qTranslate.
Version 1.0.2 | By John J. Camilleri__

and I've noticed that it is no more working with qtranslate-x.
It is very important to me using the META thing (importing the already existing tag from qTranslate META and keeping on adding them to the new pages ) and this issue will compromise the complete transition.

How to resolve? Is there any chance to let qTranslate META work with qtranslate X ?
Best,
nkint

**Comment by nkint** [comment]
EDIT:
I've activated the "Compatibility Functions" checkbox and now I can see the Multilingual META box in the Edit Page but I receive this error:

Fatal error: Call to undefined function qtrans_split() in /nas/wp/www/staging/mdlsrl/wp-content/plugins/qtranslate-meta/qtranslate-meta.php on line 109

**Comment by nkint** [comment]
(keeping on manual hand-on-dirty hacks I received also same error with qtrans_getLanguageName )

**Comment by nkint** [comment]
https://gist.github.com/nkint/a32d07e9845b961ad226
here should be a working version..

sorry I'm not very skilled with github, I will try in the weekend to make a fork and pull request to /qTranslate-Team witht he working new fork __qTranslate-X META__

**Comment by mweimerskirch** [comment]
@johnclause implemented the "qtrans_split" function in the compatibility layer of 3.2b-2. If you use the latest version from GitHub it should work.

**Comment by johnclause** [comment]
Yes, Alberto (@nkint), just use the latest from GitHub https://github.com/qTranslate-Team/qtranslate-x/archive/master.zip, the version number is not important it changes like daily ...

**Comment by nkint** [comment]
Ok so put also qtrans_getLanguageName pleanse

**Comment by johnclause** [comment]
Done, @nkint. Thanks a lot for the suggestion. Anything else is missing, that you can think of?

**Comment by johnclause** [comment]
I guess, this is closed item, please, open a new one if there is still a problem. Besides, the newer plugins like “[WordPress SEO](https://wordpress.org/plugins/wordpress-seo/)” with integrating plugin “[WordPress SEO & qTranslate-X](https://wordpress.org/plugins/wp-seo-qtranslate-x/)“, or  “[All in One SEO Pack](https://wordpress.org/plugins/all-in-one-seo-pack/)” with integrating plugin “[All in One SEO Pack & qTranslate-X](https://wordpress.org/plugins/all-in-one-seo-pack-qtranslate-x/)“ might provide similar or even more complete solution.
