### ISSUE TITLE
[3.4.6.8] Redirect Error with GET Parameters

### ISSUE THREAD

**Issue by aleks** [qTranslate-Team/qtranslate-x#599]
Hello,

I'm using the pre-path setting and wordpress permalinks are setup accordingly. My URLs look like this: `https://www.example.com/en/`.

We want to add utm-tags to track certain campaigns, so we need to add those utm-tags to our URLs:

`https://www.example.com/en/?utm_campaign=somecampaign`

qTranslate-X redirects it like this:

`https://www.example.com/en/?q=/en/&q=/en/&q=/en/&q=/en/&q=/en/&q=/en/&q=/en/&q=/en/&q=/en/&q=/en/&q=/en/&q=/en/&q=/en/&q=/en/&q=/en/&q=/en/&q=/en/&q=/en/&q=/en/&q=/en/&utm_campaign=somecampaign`

This is also the case if i try to build the whole URL with GET parameters:

`https://www.example.com/?lang=en&utm_campaign=somecampaign`

Wordpress installations without qTranslate-x do not have this issue, so this must be related to qTranslate-x.

Any ideas? :)

**Comment by aleks** [comment]
I found this (#196) pull request with a fix. But it never made it in to the final version. Any chance that this will be patched? :)

**Comment by herrvigg** [comment]
Sadly qTranslate-X is dead. We are reviving the whole project in this new repo called qTranslate-XT. You are welcome to check it out.
https://github.com/qtranslate/qtranslate-xt/

I have imported the old tickets so i'll take a look at the related issue soon or later.
