### ISSUE TITLE
How could I send you an improved qTranslate X fr_FR.po file?

### ISSUE THREAD

**Issue by isoph** [qTranslate-Team/qtranslate-x#74]
Hi
I’ve worked on translating the fr_FR.po file for qTranslate X, how can I send it to you? 
Sorry if this is not the right place to make such a request.
Regards and thanks for your work on this plugin!

**Comment by pedro-mendonca** [comment]
Can you make a pull request of the fr_FR.po and .mo files?

**Comment by isoph** [comment]
I made a pull requests on the fr_FR.po file. 
Hope I did everything right, first time doing that…
As for the .mo file, it’s raw and I can’t edit it in the browser. Can I leave you the task of compiling from the .po file? Or is there a way I didn’t see to upload my file?

**Comment by pedro-mendonca** [comment]
If you use a github client you can push both .po and .mo binary.
Either way, I think usually @johnclause compile them in every new update.

**Comment by isoph** [comment]
Ok, at the moment I don’t use a github client but I’ll look into it.

**Comment by johnclause** [comment]
@isoph: .po is sufficient though, I merged your update and generated new .mo - worked with no problems, it is on the latest master at GtHub now, - thank you!

It looks we are done with this issue? I am closing it now to save you clicks, if there is more to discuss, please, open new one.
