### ISSUE TITLE
problem with search form - qtranxf_convertURL produces wrong URL

### ISSUE THREAD

**Issue by pavelw** [qTranslate-Team/qtranslate-x#8]
Hello,

current version of plugin makes for me the wrong translation of URL.

I am switched to non-default language and trying to use search form produces wrong URL

the blog is not on home url, but on subpage: http://mypageblog/blog/

typing the query in search box produces wrong URL  http://mypageblog/blog/pl/pl/?s=dsa

commenting out in function:

    function qtranxf_fixSearchForm($form) {
    //$form = preg_replace('#action="[^"]*"#','action="'.trailingslashit(qtranxf_convertURL(get_home_url())).'"',$form);
    return $form;
    }

fixes the problem, the URL is correct: http://mypageblog/blog/pl/?s=dsa

i guess there is some kind of problem in the qtranxf_convertURL function.

more info available upon request.

best regards,
Pawel

**Comment by johnclause** [comment]
Indeed, @pavelw, this is no longer need, since we recently adjusted home_url() function to fix a number of other problems. This will be changed in release 3.0. Thanks!
