### ISSUE TITLE
How to stop add language in user-defined link in Menu ?

### ISSUE THREAD

**Issue by brucenan** [qTranslate-Team/qtranslate-x#80]
In the menu config page, I add a link part, It's good for qTranslate to set the different language name for the link, but I want to use a same link without adding a /en or other language. Is it possible to stop this function. Thanks.

**Comment by johnclause** [comment]
Have you try to read [FAQ](https://wordpress.org/plugins/qtranslate-x/faq/) "How can I prevent URL of a custom menu item from being converted"?

**Comment by brucenan** [comment]
Yes, but I've change the wordpress to solid link for friendly seo. How can I add lang=no attributes?

**Comment by johnclause** [comment]
Add query argument "setlang=no" to the URL of menu item. For example, if your URL is "http://example.com" change it to "http://example.com?setlang=no"

**Comment by brucenan** [comment]
I've tried it. But it seems not work.

**Comment by johnclause** [comment]
Indeed, this feature got broken after auto-translation of meta data was enabled. Please, test the latest version from <a href="https://github.com/qTranslate-Team/qtranslate-x">GitHub</a>, which you can download with 'Download ZIP' button on GitHub page or press <a href="https://github.com/qTranslate-Team/qtranslate-x/archive/master.zip">here</a> for the sake of convenience. I hope you do not use "QTranslate Slug", do you?

**Comment by brucenan** [comment]
Yes. The latest code is working. Thanks a lot!
Another question, can I set the totally different links for different languages in menu? Is it can be user-defined?

**Comment by johnclause** [comment]
No, such a feature is not implemented, but nothing prevents you from setting up a custom menu all together with any links you wish. I am closing this issue for now, we can still write to it and we can re-open if needed.
