### ISSUE TITLE
Compatibility with WP-Linkedin

### ISSUE THREAD

**Issue by pedro-mendonca** [qTranslate-Team/qtranslate-x#81]
Hi @johnclause 

I'm using this plugin https://wordpress.org/plugins/wp-linkedin.
It needs to be authorized with linkedin developer app with auth key etc in https://www.linkedin.com/secure/developer
The plugin need gives a URL that the user must include in Linkedin as the "OAuth 2.0 redirect URL and it's something like this http://www.yoursite.com/oauth/linkedin/

The auth won't work unless I deactivate qTranslate-x, do you know where should I investigate to debug this? Probably a url problem, I thought that deactivating qTranslate-x would work, and it did.

**Comment by johnclause** [comment]
I added '/oauth/' to the exceptions. I guess, it is safe enough, should not break anyone and will help on all methods of authentication with OAuth. Could you test the latest from GitHub?

**Comment by pedro-mendonca** [comment]
Just tested with current 3.2.8, works! :+1: 
Thanks :)

**Comment by pedro-mendonca** [comment]
With a little testing I found that qTranslate-slug is still causing the problem, now, without reverting to older version I can't say if it really was qTranslate-X problem.
Do you want me to try it to revert the option you've included or you rather just keep that /Oath exception either way?

**Comment by johnclause** [comment]
QTranslate slug is know not to behave 100% properly, although it appears more or less working. I am waiting on Pedro https://github.com/not-only-code/qtranslate-slug/issues/108. and thinking about re-implementing it under -X natively. To get it natively under -X, I guess, too many changes in their plugin are required. I was going to help them, but they even do not have their latest version on GitHub at this point, so I cannot do much except re-implementing it under -X.

The change in -X, which helped LinkedIn, is very simple, just remove '|oauth/' from the line:
>if(preg_match('#^/(wp-.*\.php|wp-admin/|xmlrpc.php|.*sitemap.*|robots.txt|oauth/)#', $path)){

if you wish to play with it.

**Comment by pedro-mendonca** [comment]
Just to end this with no loose ends, I've removed the "|oauth/" bit and it still work fine.
I'm sorry, after all, this wasn't even an issue on this but in qtranslate-slug.
I'll wait until it gets included in qtranslate as an option. :)

**Comment by freeshka77** [comment]
Asome!
