### ISSUE TITLE
GitHub updates

### ISSUE THREAD

**Issue by pedro-mendonca** [qTranslate-Team/qtranslate-x#85]
Hi @johnclause 

Do you know the plugin GitHub Updater?
https://github.com/afragen/github-updater

It allows a theme or plugin to update either from WordPress or GitHub defined repo/branch.
It uses the header info on Version and GitHub release tags.
Are you willing to try it? I'm testing it and found it somehow usefull and interesting, specially for developers.
The thing it would need from your side is just add the github repo to headers in qtranslate.php:

```
GitHub Plugin URI: https://github.com/qTranslate-Team/qtranslate-x
GitHub Branch: master
```

**Comment by johnclause** [comment]
I have just added those to the header. Will it help translators too?

**Comment by pedro-mendonca** [comment]
It's a powerfull way to keep a dev install up to date with releases or pre releases from the admin panel without ftp or the usual wait untill it's published in WordPress.
As a translator I still rely a lot in ftp as I test translations on the fly, even before I pull them to github.

**Comment by pedro-mendonca** [comment]
Even if you don't think of this as much usefull, the header is just a common information on the official repo/branch and I don't see how it can be harmful.

**Comment by pedro-mendonca** [comment]
Thanks :+1:

**Comment by johnclause** [comment]
Yes, sure, I agree.
