### ISSUE TITLE
Question: About qtranxf_use_language()

### ISSUE THREAD

**Issue by resting** [qTranslate-Team/qtranslate-x#87]
I'm curious why the `$show_available` option is set to `true` for this [line](https://github.com/qTranslate-Team/qtranslate-x/blob/3.2.7/qtranslate_frontend.php#L294)?

```
case 'post_content': $post->$key = qtranxf_use_language($lang, $txt, true); break;
```

Was trying to get WP to display the content under the default language if the one requested is empty. But  it doesn't, and shows a line of message instead. I think it means to say that only English is available or something.

Anyway, I found that that's because `$show_available` is `true`, hence [this expression](https://github.com/qTranslate-Team/qtranslate-x/blob/3.2.7/qtranslate_core.php#L1346) isn't `true`.

Setting `$show_available` to `false` works, but I'm not sure about the implications.

**Comment by johnclause** [comment]
Please, describe the original problem which you need to solve with the steps how to reproduce.

**Comment by resting** [comment]
There are some contents that I want to display in the default language while leaving the others blank. In my case, I only want to enter content in English, but leave Chinese, and Japanese tabs blank.

But WP doesn't render the default language's content, when I view in Chinese or Japanese.

Looked into the code and found the findings I stated in my first post.
Alternatively without looking into the code, is there anyway I can make WP render the English content, when viewed both in Chinese or Japanese?

**Comment by johnclause** [comment]
Did you try using option 'Hide Untranslated Content', which, btw, was modified in the latest version on github. Would that solve what you need?

**Comment by johnclause** [comment]
>Alternatively without looking into the code, is there anyway I can make WP render the English content, when viewed both in Chinese or Japanese (but leave the content area for these 2 languages blank in the backend)?

Is this the same issue: https://github.com/qTranslate-Team/qtranslate-x/issues/21?
If so, it is implemented in the latest at github, for example, https://github.com/qTranslate-Team/qtranslate-x/archive/3.2.9.8.3.zip. Please, test it.

I am closing this issue for now, we can still write into a closed issue, or we can re-open it, if needed.
