### ISSUE TITLE
Plugin description translation

### ISSUE THREAD

**Issue by pedro-mendonca** [qTranslate-Team/qtranslate-x#89]
I've been searching to automatically include the plugin description contained in header in .pot file.
So far no result, I'll keep digging and opened this issue to keep a track of this.

**Comment by pedro-mendonca** [comment]
It needs this in header, that already exists:
```
Description: Adds user-friendly and database-friendly multilingual content support into WordPress.
Text Domain: qtranslate
Domain Path: /lang/
```
What I don't know is how to automaticaly include it in the current automated process of generating the .pot file

**Comment by johnclause** [comment]
gettext framework assumes people edit this part manually. What exactly do you wish to put in?
The update script which I run replaces the most crucial parts: http://plugins.svn.wordpress.org/qtranslate-x/assets/dev/updateTranslations.sh

**Comment by pedro-mendonca** [comment]
This entry in the .pot would make the description translatable.

```
#. Description of the plugin/theme
msgid "Adds user-friendly and database-friendly multilingual content support into WordPress."
msgstr ""
```

**Comment by johnclause** [comment]
Where this string is shown?

**Comment by pedro-mendonca** [comment]
It's the description shown in the installed plugins page.

Not much important but I've seen it in other plugins and themes and immediately felt this was only 99,9% translated :)

**Comment by johnclause** [comment]
I modified the script to auto-add this line, and uploaded new .po files to master. Did you test, that it is actually shown translated in that place?

**Comment by pedro-mendonca** [comment]
Yep, it's tested and working :+1:
