### ISSUE TITLE
qTranslate-X breaks the Site Language

### ISSUE THREAD

**Issue by nkint** [qTranslate-Team/qtranslate-x#98]
Hi!
I have done a massive upgrade from mqtranslate to qtranslatex (more then 10 wordpress sites).
I've read and followed the migration notes and all configurations and translations are good so far.

But the mail language is broken in the admin panel: in english and not in italian.

On "Settings > Languages > General Settings" the default language checkbox is Italiano.
On "Settings > General" there are icons of languages and Italiano is selected.
On "Settings > General > Site Language" the Site Language dropdown menu is en_US. If I change it in Italiano the page is refreshed, there is a message on the top of the page about good setting saving ("Impostazioni salvate") but the admin panel is still in english, and the dropdown menu Site Language is setted to en_US while I'm expecting to see Italiano.

If I deactivate the qTranslate-X plugin the admin panel is in Italian. If I activate the qTranslate-X plugin the admin panel is in english and there is no way to change it.

What can I try?

**Comment by johnclause** [comment]
Has that started happening after an update, or you are the first time user? What did you use before -qTranslate-X?  Do you see the menu language switcher on the top-right corner of admin bar? q-X takes control of the site language and normally menu at the top-right works. The default language is changed to English after q-X install. You have to add Italian to the list of languages, and then you can switch to Italian via menu at top-right. This is a know imperfection, we will adjust soon.

**Comment by nkint** [comment]
Ok I've seen it.
It seems to resolve the problem, thanks.
I didn't notice it, maybe add an additional NOTE on the migration document? Have I missed it?

**Comment by johnclause** [comment]
Yes, we lack a good documentation. Also working on it.

**Comment by nkint** [comment]
Again here sorry. I tried one of the blog with a different computer and different browser and.. the problem is the same, it is in english. Is it a cookie related thing? Is there a way to change it permanently to Italian?
Also, the default language with a fresh computer/browser is in english, so that:
www.mycoolblog.it/en
is the default redirect while I would like that the main lang is the italina..
no way to change it?

**Comment by qtranslateteam** [comment]
Yes, it keep the current selection in cookie. If cookie is not set, then it
is the default language. Is Italian the default in your case?

**Comment by nkint** [comment]
I think yes.

Mainly because if I deactivate qTranslateX the wp admin is in italian.

But I cannot be sure because with qTranslateX activated if I try to change the language under "Settings > General > Site Language" dropdown menu my choice is ignored and qTranslateX se always en_US as I explained in the first issue post.

I had before mqtranslate, but I have checked the "import configurations from mqtranslate" in Import/export setting panel.

**Comment by johnclause** [comment]
I mean default in -X configuration.

**Comment by nkint** [comment]
where do I set it?

**Comment by qtranslateteam** [comment]
-X configuration page, Settings/Languages:
/wp-admin/options-general.php?page=qtranslate-x

**Comment by nkint** [comment]
Yes it is: Italian is the first and checkboxed. 
But if I open the page with an anonymous browser session the admin panel is in english.

**Comment by nkint** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/609314/6829657/1cf12652-d315-11e4-8093-49ea664cd4be.png)

If I have understood correctly:
in a fresh anynimous browser window, the qtranslateX default language is in italian but at top right corner there is a british flag..
I'm still missing something?

**Comment by johnclause** [comment]
I am not sure, maybe it does not do anything then, just keeps language from WP. If you deactivate -X, what language is shown on page /wp-admin/options-general.php? Set it to Italian too and do not change it manually when q-X is active.

**Comment by johnclause** [comment]
Indeed the default was taken from WP instead of q-X default. This is supposed to be improved now in 3.2.9.3. If you wish to try it: https://github.com/qTranslate-Team/qtranslate-x/archive/3.2.9.3.zip

**Comment by nkint** [comment]
OK, this new version resolve the global language roblem but it is breaking the qTranslate-SLUG plugin (it does not work and it does not recognize that qTranslateX is installed)

**Comment by nkint** [comment]
(I don't know if this issue has visibility due to its closed status, if no feedback I will open a new issue for qtranslate slug support in the next days..)

**Comment by johnclause** [comment]
Yes, I still get e-mails and notifications even if issue is closed. Slug issue is known to us and to -slug developers: https://github.com/not-only-code/qtranslate-slug/issues/108,  and is on the list. Opening a new issue would not accelerate the things.

**Comment by LC43** [comment]
hi! i've updated our code to fix this issue. the language widget now has the url with the lang.

for example, if fr is your default language, the links in the menu now have 

`domain.tldl/fr/url-francais`

then its redirected to 

`domain.tld/url-francais/`

its a workaround, but hey, its sunday :))
